/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for actions requested of an alarm event responder.
        /// </summary>
        /// <value>A data type for actions requested of an alarm event responder.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ApcoAlarmEventResponseActionCodeSimpleType
        {
            /// <summary>
            /// Enum NotifyEnum for notify
            /// </summary>
            [EnumMember(Value = "notify")]
            NotifyEnum = 0,
            /// <summary>
            /// Enum RespondEnum for respond
            /// </summary>
            [EnumMember(Value = "respond")]
            RespondEnum = 1        }
}
