/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for a known scale units that indicates whether the known scales units are in inches or millimeters.
        /// </summary>
        /// <value>A data type for a known scale units that indicates whether the known scales units are in inches or millimeters.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum BiomResolutionScaleUnitCodeSimpleType
        {
            /// <summary>
            /// Enum INEnum for IN
            /// </summary>
            [EnumMember(Value = "IN")]
            INEnum = 0,
            /// <summary>
            /// Enum MMEnum for MM
            /// </summary>
            [EnumMember(Value = "MM")]
            MMEnum = 1        }
}
