/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
    /// <summary>
    /// A data type for a single minutia, as defined by the ANSI INCITS 378-2004 Standard
    /// </summary>
    [DataContract]
    public partial class BiomINCITSMinutiaType : IEquatable<BiomINCITSMinutiaType>
    { 
        /// <summary>
        /// An index identifier for uniquely denoting a minutia NIEM reference is biom:MinutiaID
        /// </summary>
        /// <value>An index identifier for uniquely denoting a minutia NIEM reference is biom:MinutiaID</value>

        [DataMember(Name="minutiaId")]
        public List<NiemXspositiveInteger> MinutiaId { get; set; }

        /// <summary>
        /// A location of one minutia in a friction ridge image, as defined by the ANSI INCITS 378-2004 Standard NIEM reference is biom:INCITSMinutiaLocation
        /// </summary>
        /// <value>A location of one minutia in a friction ridge image, as defined by the ANSI INCITS 378-2004 Standard NIEM reference is biom:INCITSMinutiaLocation</value>

        [DataMember(Name="location")]
        public List<BiomFingerprintFeatureLocationType> Location { get; set; }

        /// <summary>
        /// A kind of minutia (e.g. ridge ending, bifurcation, or other), as defined by the ANSI INCITS 378-2004 Standard NIEM reference is biom:INCITSMinutiaCategoryCode
        /// </summary>
        /// <value>A kind of minutia (e.g. ridge ending, bifurcation, or other), as defined by the ANSI INCITS 378-2004 Standard NIEM reference is biom:INCITSMinutiaCategoryCode</value>

        [DataMember(Name="categoryCode")]
        public List<BiomINCITSMinutiaCategoryCodeType> CategoryCode { get; set; }

        /// <summary>
        /// A quality value assigned to a minutia NIEM reference is biom:MinutiaQualityValue
        /// </summary>
        /// <value>A quality value assigned to a minutia NIEM reference is biom:MinutiaQualityValue</value>

        [DataMember(Name="minutiaQualityValue")]
        public List<BiomInteger0to100Type> MinutiaQualityValue { get; set; }

        /// <summary>
        /// biomINCITSMinutiaType JSON-LD context
        /// </summary>
        /// <value>biomINCITSMinutiaType JSON-LD context</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ContextEnum
        {
            /// <summary>
            /// Enum JSONLDContextsbiomINCITSMinutiaTypeContextJsonldEnum for ../JSON-LD_Contexts/biomINCITSMinutiaTypeContext.jsonld
            /// </summary>
            [EnumMember(Value = "../JSON-LD_Contexts/biomINCITSMinutiaTypeContext.jsonld")]
            JSONLDContextsbiomINCITSMinutiaTypeContextJsonldEnum = 0        }

        /// <summary>
        /// biomINCITSMinutiaType JSON-LD context
        /// </summary>
        /// <value>biomINCITSMinutiaType JSON-LD context</value>

        [DataMember(Name="@context")]
        public ContextEnum? Context { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BiomINCITSMinutiaType {\n");
            sb.Append("  MinutiaId: ").Append(MinutiaId).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  CategoryCode: ").Append(CategoryCode).Append("\n");
            sb.Append("  MinutiaQualityValue: ").Append(MinutiaQualityValue).Append("\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BiomINCITSMinutiaType)obj);
        }

        /// <summary>
        /// Returns true if BiomINCITSMinutiaType instances are equal
        /// </summary>
        /// <param name="other">Instance of BiomINCITSMinutiaType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BiomINCITSMinutiaType other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MinutiaId == other.MinutiaId ||
                    MinutiaId != null &&
                    MinutiaId.SequenceEqual(other.MinutiaId)
                ) && 
                (
                    Location == other.Location ||
                    Location != null &&
                    Location.SequenceEqual(other.Location)
                ) && 
                (
                    CategoryCode == other.CategoryCode ||
                    CategoryCode != null &&
                    CategoryCode.SequenceEqual(other.CategoryCode)
                ) && 
                (
                    MinutiaQualityValue == other.MinutiaQualityValue ||
                    MinutiaQualityValue != null &&
                    MinutiaQualityValue.SequenceEqual(other.MinutiaQualityValue)
                ) && 
                (
                    Context == other.Context ||
                    Context != null &&
                    Context.Equals(other.Context)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MinutiaId != null)
                    hashCode = hashCode * 59 + MinutiaId.GetHashCode();
                    if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();
                    if (CategoryCode != null)
                    hashCode = hashCode * 59 + CategoryCode.GetHashCode();
                    if (MinutiaQualityValue != null)
                    hashCode = hashCode * 59 + MinutiaQualityValue.GetHashCode();
                    if (Context != null)
                    hashCode = hashCode * 59 + Context.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BiomINCITSMinutiaType left, BiomINCITSMinutiaType right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BiomINCITSMinutiaType left, BiomINCITSMinutiaType right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
