/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
    /// <summary>
    /// A data type for a confidence in a ridge count between two points
    /// </summary>
    [DataContract]
    public partial class BiomMinutiaeRidgeCountConfidenceType : IEquatable<BiomMinutiaeRidgeCountConfidenceType>
    { 
        /// <summary>
        /// A vertex in a position path NIEM reference is biom:ImageFeatureVertex
        /// </summary>
        /// <value>A vertex in a position path NIEM reference is biom:ImageFeatureVertex</value>

        [DataMember(Name="imageFeatureVertex")]
        public List<BiomVertexType> ImageFeatureVertex { get; set; }

        /// <summary>
        /// A method of counting ridges NIEM reference is biom:MinutiaeRidgeCountMethodCode
        /// </summary>
        /// <value>A method of counting ridges NIEM reference is biom:MinutiaeRidgeCountMethodCode</value>

        [DataMember(Name="minutiaeRidgeCountMethodCode")]
        public List<BiomMinutiaeRidgeCountMethodCodeType> MinutiaeRidgeCountMethodCode { get; set; }

        /// <summary>
        /// A degree of confidence in a ridge count between two points NIEM reference is biom:MinutiaeRidgeCountConfidenceValue
        /// </summary>
        /// <value>A degree of confidence in a ridge count between two points NIEM reference is biom:MinutiaeRidgeCountConfidenceValue</value>

        [DataMember(Name="value")]
        public List<BiomMinutiaeRidgeCountConfidenceValueType> Value { get; set; }

        /// <summary>
        /// biomMinutiaeRidgeCountConfidenceType JSON-LD context
        /// </summary>
        /// <value>biomMinutiaeRidgeCountConfidenceType JSON-LD context</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ContextEnum
        {
            /// <summary>
            /// Enum JSONLDContextsbiomMinutiaeRidgeCountConfidenceTypeContextJsonldEnum for ../JSON-LD_Contexts/biomMinutiaeRidgeCountConfidenceTypeContext.jsonld
            /// </summary>
            [EnumMember(Value = "../JSON-LD_Contexts/biomMinutiaeRidgeCountConfidenceTypeContext.jsonld")]
            JSONLDContextsbiomMinutiaeRidgeCountConfidenceTypeContextJsonldEnum = 0        }

        /// <summary>
        /// biomMinutiaeRidgeCountConfidenceType JSON-LD context
        /// </summary>
        /// <value>biomMinutiaeRidgeCountConfidenceType JSON-LD context</value>

        [DataMember(Name="@context")]
        public ContextEnum? Context { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BiomMinutiaeRidgeCountConfidenceType {\n");
            sb.Append("  ImageFeatureVertex: ").Append(ImageFeatureVertex).Append("\n");
            sb.Append("  MinutiaeRidgeCountMethodCode: ").Append(MinutiaeRidgeCountMethodCode).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BiomMinutiaeRidgeCountConfidenceType)obj);
        }

        /// <summary>
        /// Returns true if BiomMinutiaeRidgeCountConfidenceType instances are equal
        /// </summary>
        /// <param name="other">Instance of BiomMinutiaeRidgeCountConfidenceType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BiomMinutiaeRidgeCountConfidenceType other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ImageFeatureVertex == other.ImageFeatureVertex ||
                    ImageFeatureVertex != null &&
                    ImageFeatureVertex.SequenceEqual(other.ImageFeatureVertex)
                ) && 
                (
                    MinutiaeRidgeCountMethodCode == other.MinutiaeRidgeCountMethodCode ||
                    MinutiaeRidgeCountMethodCode != null &&
                    MinutiaeRidgeCountMethodCode.SequenceEqual(other.MinutiaeRidgeCountMethodCode)
                ) && 
                (
                    Value == other.Value ||
                    Value != null &&
                    Value.SequenceEqual(other.Value)
                ) && 
                (
                    Context == other.Context ||
                    Context != null &&
                    Context.Equals(other.Context)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ImageFeatureVertex != null)
                    hashCode = hashCode * 59 + ImageFeatureVertex.GetHashCode();
                    if (MinutiaeRidgeCountMethodCode != null)
                    hashCode = hashCode * 59 + MinutiaeRidgeCountMethodCode.GetHashCode();
                    if (Value != null)
                    hashCode = hashCode * 59 + Value.GetHashCode();
                    if (Context != null)
                    hashCode = hashCode * 59 + Context.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BiomMinutiaeRidgeCountConfidenceType left, BiomMinutiaeRidgeCountConfidenceType right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BiomMinutiaeRidgeCountConfidenceType left, BiomMinutiaeRidgeCountConfidenceType right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
