/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for a result of an examiner's assessment of the value of the friction ridge impression
        /// </summary>
        /// <value>A data type for a result of an examiner's assessment of the value of the friction ridge impression</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum BiomMinutiaeValueAssessmentResultCodeSimpleType
        {
            /// <summary>
            /// Enum LIMITEDEnum for LIMITED
            /// </summary>
            [EnumMember(Value = "LIMITED")]
            LIMITEDEnum = 0,
            /// <summary>
            /// Enum NONPRINTEnum for NONPRINT
            /// </summary>
            [EnumMember(Value = "NONPRINT")]
            NONPRINTEnum = 1,
            /// <summary>
            /// Enum NOVALUEEnum for NOVALUE
            /// </summary>
            [EnumMember(Value = "NOVALUE")]
            NOVALUEEnum = 2,
            /// <summary>
            /// Enum VALUEEnum for VALUE
            /// </summary>
            [EnumMember(Value = "VALUE")]
            VALUEEnum = 3        }
}
