/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
    /// <summary>
    /// A data type for a missing area of a palm print image
    /// </summary>
    [DataContract]
    public partial class BiomPalmPrintImageMissingAreaType : IEquatable<BiomPalmPrintImageMissingAreaType>
    { 
        /// <summary>
        /// A location on the palm that a print represents NIEM reference is biom:PalmPositionCode
        /// </summary>
        /// <value>A location on the palm that a print represents NIEM reference is biom:PalmPositionCode</value>

        [DataMember(Name="palmPositionCode")]
        public List<BiomPalmPositionCodeType> PalmPositionCode { get; set; }

        /// <summary>
        /// A reason for a missing area of a palm print image NIEM reference is biom:PalmMissingAreaReasonCode
        /// </summary>
        /// <value>A reason for a missing area of a palm print image NIEM reference is biom:PalmMissingAreaReasonCode</value>

        [DataMember(Name="palmMissingAreaReasonCode")]
        public List<BiomFingerprintImageMissingAreaReasonCodeType> PalmMissingAreaReasonCode { get; set; }

        /// <summary>
        /// biomPalmPrintImageMissingAreaType JSON-LD context
        /// </summary>
        /// <value>biomPalmPrintImageMissingAreaType JSON-LD context</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ContextEnum
        {
            /// <summary>
            /// Enum JSONLDContextsbiomPalmPrintImageMissingAreaTypeContextJsonldEnum for ../JSON-LD_Contexts/biomPalmPrintImageMissingAreaTypeContext.jsonld
            /// </summary>
            [EnumMember(Value = "../JSON-LD_Contexts/biomPalmPrintImageMissingAreaTypeContext.jsonld")]
            JSONLDContextsbiomPalmPrintImageMissingAreaTypeContextJsonldEnum = 0        }

        /// <summary>
        /// biomPalmPrintImageMissingAreaType JSON-LD context
        /// </summary>
        /// <value>biomPalmPrintImageMissingAreaType JSON-LD context</value>

        [DataMember(Name="@context")]
        public ContextEnum? Context { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BiomPalmPrintImageMissingAreaType {\n");
            sb.Append("  PalmPositionCode: ").Append(PalmPositionCode).Append("\n");
            sb.Append("  PalmMissingAreaReasonCode: ").Append(PalmMissingAreaReasonCode).Append("\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BiomPalmPrintImageMissingAreaType)obj);
        }

        /// <summary>
        /// Returns true if BiomPalmPrintImageMissingAreaType instances are equal
        /// </summary>
        /// <param name="other">Instance of BiomPalmPrintImageMissingAreaType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BiomPalmPrintImageMissingAreaType other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PalmPositionCode == other.PalmPositionCode ||
                    PalmPositionCode != null &&
                    PalmPositionCode.SequenceEqual(other.PalmPositionCode)
                ) && 
                (
                    PalmMissingAreaReasonCode == other.PalmMissingAreaReasonCode ||
                    PalmMissingAreaReasonCode != null &&
                    PalmMissingAreaReasonCode.SequenceEqual(other.PalmMissingAreaReasonCode)
                ) && 
                (
                    Context == other.Context ||
                    Context != null &&
                    Context.Equals(other.Context)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PalmPositionCode != null)
                    hashCode = hashCode * 59 + PalmPositionCode.GetHashCode();
                    if (PalmMissingAreaReasonCode != null)
                    hashCode = hashCode * 59 + PalmMissingAreaReasonCode.GetHashCode();
                    if (Context != null)
                    hashCode = hashCode * 59 + Context.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BiomPalmPrintImageMissingAreaType left, BiomPalmPrintImageMissingAreaType right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BiomPalmPrintImageMissingAreaType left, BiomPalmPrintImageMissingAreaType right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
