/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for a kind of evidence of friction ridge impression fraud
        /// </summary>
        /// <value>A data type for a kind of evidence of friction ridge impression fraud</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum BiomMinutiaeFraudEvidenceCategoryCodeSimpleType
        {
            /// <summary>
            /// Enum EVAEnum for EVA
            /// </summary>
            [EnumMember(Value = "EVA")]
            EVAEnum = 0,
            /// <summary>
            /// Enum FABEnum for FAB
            /// </summary>
            [EnumMember(Value = "FAB")]
            FABEnum = 1,
            /// <summary>
            /// Enum FOREnum for FOR
            /// </summary>
            [EnumMember(Value = "FOR")]
            FOREnum = 2,
            /// <summary>
            /// Enum SPOEnum for SPO
            /// </summary>
            [EnumMember(Value = "SPO")]
            SPOEnum = 3        }
}
