/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for the level of restoration and surface information coded in Field 12.010: Tooth data detail / TDD.
        /// </summary>
        /// <value>A data type for the level of restoration and surface information coded in Field 12.010: Tooth data detail / TDD.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum BiomRestorationDataGranularityCodeSimpleType
        {
            /// <summary>
            /// Enum NUMBER_11 for 11
            /// </summary>
            [EnumMember(Value = "11")]
            NUMBER_11 = 0,
            /// <summary>
            /// Enum NUMBER_21 for 21
            /// </summary>
            [EnumMember(Value = "21")]
            NUMBER_21 = 1,
            /// <summary>
            /// Enum NUMBER_31 for 31
            /// </summary>
            [EnumMember(Value = "31")]
            NUMBER_31 = 2,
            /// <summary>
            /// Enum NUMBER_41 for 41
            /// </summary>
            [EnumMember(Value = "41")]
            NUMBER_41 = 3,
            /// <summary>
            /// Enum NUMBER_51 for 51
            /// </summary>
            [EnumMember(Value = "51")]
            NUMBER_51 = 4,
            /// <summary>
            /// Enum NUMBER_99 for 99
            /// </summary>
            [EnumMember(Value = "99")]
            NUMBER_99 = 5        }
}
