/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for a kind of electronic equipment.
        /// </summary>
        /// <value>A data type for a kind of electronic equipment.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CommodityElectronicEquipmentCategoryCodeSimpleType
        {
            /// <summary>
            /// Enum NUMBER_35000 for 35000
            /// </summary>
            [EnumMember(Value = "35000")]
            NUMBER_35000 = 0,
            /// <summary>
            /// Enum NUMBER_35100 for 35100
            /// </summary>
            [EnumMember(Value = "35100")]
            NUMBER_35100 = 1,
            /// <summary>
            /// Enum NUMBER_35110 for 35110
            /// </summary>
            [EnumMember(Value = "35110")]
            NUMBER_35110 = 2,
            /// <summary>
            /// Enum NUMBER_35120 for 35120
            /// </summary>
            [EnumMember(Value = "35120")]
            NUMBER_35120 = 3,
            /// <summary>
            /// Enum NUMBER_35200 for 35200
            /// </summary>
            [EnumMember(Value = "35200")]
            NUMBER_35200 = 4,
            /// <summary>
            /// Enum NUMBER_35210 for 35210
            /// </summary>
            [EnumMember(Value = "35210")]
            NUMBER_35210 = 5,
            /// <summary>
            /// Enum NUMBER_35220 for 35220
            /// </summary>
            [EnumMember(Value = "35220")]
            NUMBER_35220 = 6,
            /// <summary>
            /// Enum NUMBER_35300 for 35300
            /// </summary>
            [EnumMember(Value = "35300")]
            NUMBER_35300 = 7,
            /// <summary>
            /// Enum NUMBER_35310 for 35310
            /// </summary>
            [EnumMember(Value = "35310")]
            NUMBER_35310 = 8,
            /// <summary>
            /// Enum NUMBER_35390 for 35390
            /// </summary>
            [EnumMember(Value = "35390")]
            NUMBER_35390 = 9,
            /// <summary>
            /// Enum NUMBER_35400 for 35400
            /// </summary>
            [EnumMember(Value = "35400")]
            NUMBER_35400 = 10,
            /// <summary>
            /// Enum NUMBER_35500 for 35500
            /// </summary>
            [EnumMember(Value = "35500")]
            NUMBER_35500 = 11,
            /// <summary>
            /// Enum NUMBER_35510 for 35510
            /// </summary>
            [EnumMember(Value = "35510")]
            NUMBER_35510 = 12,
            /// <summary>
            /// Enum NUMBER_35520 for 35520
            /// </summary>
            [EnumMember(Value = "35520")]
            NUMBER_35520 = 13,
            /// <summary>
            /// Enum NUMBER_35600 for 35600
            /// </summary>
            [EnumMember(Value = "35600")]
            NUMBER_35600 = 14,
            /// <summary>
            /// Enum NUMBER_35610 for 35610
            /// </summary>
            [EnumMember(Value = "35610")]
            NUMBER_35610 = 15,
            /// <summary>
            /// Enum NUMBER_35621 for 35621
            /// </summary>
            [EnumMember(Value = "35621")]
            NUMBER_35621 = 16,
            /// <summary>
            /// Enum NUMBER_35629 for 35629
            /// </summary>
            [EnumMember(Value = "35629")]
            NUMBER_35629 = 17,
            /// <summary>
            /// Enum NUMBER_35700 for 35700
            /// </summary>
            [EnumMember(Value = "35700")]
            NUMBER_35700 = 18,
            /// <summary>
            /// Enum NUMBER_35800 for 35800
            /// </summary>
            [EnumMember(Value = "35800")]
            NUMBER_35800 = 19,
            /// <summary>
            /// Enum NUMBER_35811 for 35811
            /// </summary>
            [EnumMember(Value = "35811")]
            NUMBER_35811 = 20,
            /// <summary>
            /// Enum NUMBER_35812 for 35812
            /// </summary>
            [EnumMember(Value = "35812")]
            NUMBER_35812 = 21,
            /// <summary>
            /// Enum NUMBER_35813 for 35813
            /// </summary>
            [EnumMember(Value = "35813")]
            NUMBER_35813 = 22,
            /// <summary>
            /// Enum NUMBER_35814 for 35814
            /// </summary>
            [EnumMember(Value = "35814")]
            NUMBER_35814 = 23,
            /// <summary>
            /// Enum NUMBER_35820 for 35820
            /// </summary>
            [EnumMember(Value = "35820")]
            NUMBER_35820 = 24,
            /// <summary>
            /// Enum NUMBER_35900 for 35900
            /// </summary>
            [EnumMember(Value = "35900")]
            NUMBER_35900 = 25,
            /// <summary>
            /// Enum NUMBER_35912 for 35912
            /// </summary>
            [EnumMember(Value = "35912")]
            NUMBER_35912 = 26,
            /// <summary>
            /// Enum NUMBER_35920 for 35920
            /// </summary>
            [EnumMember(Value = "35920")]
            NUMBER_35920 = 27,
            /// <summary>
            /// Enum NUMBER_35991 for 35991
            /// </summary>
            [EnumMember(Value = "35991")]
            NUMBER_35991 = 28,
            /// <summary>
            /// Enum NUMBER_35992 for 35992
            /// </summary>
            [EnumMember(Value = "35992")]
            NUMBER_35992 = 29,
            /// <summary>
            /// Enum NUMBER_35993 for 35993
            /// </summary>
            [EnumMember(Value = "35993")]
            NUMBER_35993 = 30,
            /// <summary>
            /// Enum NUMBER_35994 for 35994
            /// </summary>
            [EnumMember(Value = "35994")]
            NUMBER_35994 = 31,
            /// <summary>
            /// Enum NUMBER_35995 for 35995
            /// </summary>
            [EnumMember(Value = "35995")]
            NUMBER_35995 = 32,
            /// <summary>
            /// Enum NUMBER_35999 for 35999
            /// </summary>
            [EnumMember(Value = "35999")]
            NUMBER_35999 = 33        }
}
