/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for 2.2: Country Codes
        /// </summary>
        /// <value>A data type for 2.2: Country Codes</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NcicCountryCodeSimpleType
        {
            /// <summary>
            /// Enum _0CEnum for 0C
            /// </summary>
            [EnumMember(Value = "0C")]
            _0CEnum = 0,
            /// <summary>
            /// Enum NUMBER_0F for 0F
            /// </summary>
            [EnumMember(Value = "0F")]
            NUMBER_0F = 1,
            /// <summary>
            /// Enum _0IEnum for 0I
            /// </summary>
            [EnumMember(Value = "0I")]
            _0IEnum = 2,
            /// <summary>
            /// Enum _0MEnum for 0M
            /// </summary>
            [EnumMember(Value = "0M")]
            _0MEnum = 3,
            /// <summary>
            /// Enum A0Enum for A0
            /// </summary>
            [EnumMember(Value = "A0")]
            A0Enum = 4,
            /// <summary>
            /// Enum AAEnum for AA
            /// </summary>
            [EnumMember(Value = "AA")]
            AAEnum = 5,
            /// <summary>
            /// Enum ADEnum for AD
            /// </summary>
            [EnumMember(Value = "AD")]
            ADEnum = 6,
            /// <summary>
            /// Enum AEEnum for AE
            /// </summary>
            [EnumMember(Value = "AE")]
            AEEnum = 7,
            /// <summary>
            /// Enum AFEnum for AF
            /// </summary>
            [EnumMember(Value = "AF")]
            AFEnum = 8,
            /// <summary>
            /// Enum AHEnum for AH
            /// </summary>
            [EnumMember(Value = "AH")]
            AHEnum = 9,
            /// <summary>
            /// Enum AIEnum for AI
            /// </summary>
            [EnumMember(Value = "AI")]
            AIEnum = 10,
            /// <summary>
            /// Enum AJEnum for AJ
            /// </summary>
            [EnumMember(Value = "AJ")]
            AJEnum = 11,
            /// <summary>
            /// Enum ANEnum for AN
            /// </summary>
            [EnumMember(Value = "AN")]
            ANEnum = 12,
            /// <summary>
            /// Enum APEnum for AP
            /// </summary>
            [EnumMember(Value = "AP")]
            APEnum = 13,
            /// <summary>
            /// Enum AQEnum for AQ
            /// </summary>
            [EnumMember(Value = "AQ")]
            AQEnum = 14,
            /// <summary>
            /// Enum ASEnum for AS
            /// </summary>
            [EnumMember(Value = "AS")]
            ASEnum = 15,
            /// <summary>
            /// Enum ATEnum for AT
            /// </summary>
            [EnumMember(Value = "AT")]
            ATEnum = 16,
            /// <summary>
            /// Enum AUEnum for AU
            /// </summary>
            [EnumMember(Value = "AU")]
            AUEnum = 17,
            /// <summary>
            /// Enum AVEnum for AV
            /// </summary>
            [EnumMember(Value = "AV")]
            AVEnum = 18,
            /// <summary>
            /// Enum B0Enum for B0
            /// </summary>
            [EnumMember(Value = "B0")]
            B0Enum = 19,
            /// <summary>
            /// Enum BBEnum for BB
            /// </summary>
            [EnumMember(Value = "BB")]
            BBEnum = 20,
            /// <summary>
            /// Enum BDEnum for BD
            /// </summary>
            [EnumMember(Value = "BD")]
            BDEnum = 21,
            /// <summary>
            /// Enum BEEnum for BE
            /// </summary>
            [EnumMember(Value = "BE")]
            BEEnum = 22,
            /// <summary>
            /// Enum BFEnum for BF
            /// </summary>
            [EnumMember(Value = "BF")]
            BFEnum = 23,
            /// <summary>
            /// Enum BGEnum for BG
            /// </summary>
            [EnumMember(Value = "BG")]
            BGEnum = 24,
            /// <summary>
            /// Enum BHEnum for BH
            /// </summary>
            [EnumMember(Value = "BH")]
            BHEnum = 25,
            /// <summary>
            /// Enum BIEnum for BI
            /// </summary>
            [EnumMember(Value = "BI")]
            BIEnum = 26,
            /// <summary>
            /// Enum BLEnum for BL
            /// </summary>
            [EnumMember(Value = "BL")]
            BLEnum = 27,
            /// <summary>
            /// Enum BMEnum for BM
            /// </summary>
            [EnumMember(Value = "BM")]
            BMEnum = 28,
            /// <summary>
            /// Enum BNEnum for BN
            /// </summary>
            [EnumMember(Value = "BN")]
            BNEnum = 29,
            /// <summary>
            /// Enum BPEnum for BP
            /// </summary>
            [EnumMember(Value = "BP")]
            BPEnum = 30,
            /// <summary>
            /// Enum BQEnum for BQ
            /// </summary>
            [EnumMember(Value = "BQ")]
            BQEnum = 31,
            /// <summary>
            /// Enum BREnum for BR
            /// </summary>
            [EnumMember(Value = "BR")]
            BREnum = 32,
            /// <summary>
            /// Enum BSEnum for BS
            /// </summary>
            [EnumMember(Value = "BS")]
            BSEnum = 33,
            /// <summary>
            /// Enum BTEnum for BT
            /// </summary>
            [EnumMember(Value = "BT")]
            BTEnum = 34,
            /// <summary>
            /// Enum BUEnum for BU
            /// </summary>
            [EnumMember(Value = "BU")]
            BUEnum = 35,
            /// <summary>
            /// Enum BVEnum for BV
            /// </summary>
            [EnumMember(Value = "BV")]
            BVEnum = 36,
            /// <summary>
            /// Enum BWEnum for BW
            /// </summary>
            [EnumMember(Value = "BW")]
            BWEnum = 37,
            /// <summary>
            /// Enum BXEnum for BX
            /// </summary>
            [EnumMember(Value = "BX")]
            BXEnum = 38,
            /// <summary>
            /// Enum BYEnum for BY
            /// </summary>
            [EnumMember(Value = "BY")]
            BYEnum = 39,
            /// <summary>
            /// Enum BZEnum for BZ
            /// </summary>
            [EnumMember(Value = "BZ")]
            BZEnum = 40,
            /// <summary>
            /// Enum CBEnum for CB
            /// </summary>
            [EnumMember(Value = "CB")]
            CBEnum = 41,
            /// <summary>
            /// Enum CCEnum for CC
            /// </summary>
            [EnumMember(Value = "CC")]
            CCEnum = 42,
            /// <summary>
            /// Enum CDEnum for CD
            /// </summary>
            [EnumMember(Value = "CD")]
            CDEnum = 43,
            /// <summary>
            /// Enum CFEnum for CF
            /// </summary>
            [EnumMember(Value = "CF")]
            CFEnum = 44,
            /// <summary>
            /// Enum CJEnum for CJ
            /// </summary>
            [EnumMember(Value = "CJ")]
            CJEnum = 45,
            /// <summary>
            /// Enum CMEnum for CM
            /// </summary>
            [EnumMember(Value = "CM")]
            CMEnum = 46,
            /// <summary>
            /// Enum CPEnum for CP
            /// </summary>
            [EnumMember(Value = "CP")]
            CPEnum = 47,
            /// <summary>
            /// Enum CQEnum for CQ
            /// </summary>
            [EnumMember(Value = "CQ")]
            CQEnum = 48,
            /// <summary>
            /// Enum CREnum for CR
            /// </summary>
            [EnumMember(Value = "CR")]
            CREnum = 49,
            /// <summary>
            /// Enum CSEnum for CS
            /// </summary>
            [EnumMember(Value = "CS")]
            CSEnum = 50,
            /// <summary>
            /// Enum CVEnum for CV
            /// </summary>
            [EnumMember(Value = "CV")]
            CVEnum = 51,
            /// <summary>
            /// Enum CWEnum for CW
            /// </summary>
            [EnumMember(Value = "CW")]
            CWEnum = 52,
            /// <summary>
            /// Enum CYEnum for CY
            /// </summary>
            [EnumMember(Value = "CY")]
            CYEnum = 53,
            /// <summary>
            /// Enum DBEnum for DB
            /// </summary>
            [EnumMember(Value = "DB")]
            DBEnum = 54,
            /// <summary>
            /// Enum DDEnum for DD
            /// </summary>
            [EnumMember(Value = "DD")]
            DDEnum = 55,
            /// <summary>
            /// Enum DGEnum for DG
            /// </summary>
            [EnumMember(Value = "DG")]
            DGEnum = 56,
            /// <summary>
            /// Enum DHEnum for DH
            /// </summary>
            [EnumMember(Value = "DH")]
            DHEnum = 57,
            /// <summary>
            /// Enum DIEnum for DI
            /// </summary>
            [EnumMember(Value = "DI")]
            DIEnum = 58,
            /// <summary>
            /// Enum DJEnum for DJ
            /// </summary>
            [EnumMember(Value = "DJ")]
            DJEnum = 59,
            /// <summary>
            /// Enum DKEnum for DK
            /// </summary>
            [EnumMember(Value = "DK")]
            DKEnum = 60,
            /// <summary>
            /// Enum DMEnum for DM
            /// </summary>
            [EnumMember(Value = "DM")]
            DMEnum = 61,
            /// <summary>
            /// Enum DNEnum for DN
            /// </summary>
            [EnumMember(Value = "DN")]
            DNEnum = 62,
            /// <summary>
            /// Enum DREnum for DR
            /// </summary>
            [EnumMember(Value = "DR")]
            DREnum = 63,
            /// <summary>
            /// Enum E0Enum for E0
            /// </summary>
            [EnumMember(Value = "E0")]
            E0Enum = 64,
            /// <summary>
            /// Enum EKEnum for EK
            /// </summary>
            [EnumMember(Value = "EK")]
            EKEnum = 65,
            /// <summary>
            /// Enum ELEnum for EL
            /// </summary>
            [EnumMember(Value = "EL")]
            ELEnum = 66,
            /// <summary>
            /// Enum ENEnum for EN
            /// </summary>
            [EnumMember(Value = "EN")]
            ENEnum = 67,
            /// <summary>
            /// Enum EREnum for ER
            /// </summary>
            [EnumMember(Value = "ER")]
            EREnum = 68,
            /// <summary>
            /// Enum ESEnum for ES
            /// </summary>
            [EnumMember(Value = "ES")]
            ESEnum = 69,
            /// <summary>
            /// Enum ETEnum for ET
            /// </summary>
            [EnumMember(Value = "ET")]
            ETEnum = 70,
            /// <summary>
            /// Enum EUEnum for EU
            /// </summary>
            [EnumMember(Value = "EU")]
            EUEnum = 71,
            /// <summary>
            /// Enum EYEnum for EY
            /// </summary>
            [EnumMember(Value = "EY")]
            EYEnum = 72,
            /// <summary>
            /// Enum EZEnum for EZ
            /// </summary>
            [EnumMember(Value = "EZ")]
            EZEnum = 73,
            /// <summary>
            /// Enum F0Enum for F0
            /// </summary>
            [EnumMember(Value = "F0")]
            F0Enum = 74,
            /// <summary>
            /// Enum FAEnum for FA
            /// </summary>
            [EnumMember(Value = "FA")]
            FAEnum = 75,
            /// <summary>
            /// Enum FDEnum for FD
            /// </summary>
            [EnumMember(Value = "FD")]
            FDEnum = 76,
            /// <summary>
            /// Enum FGEnum for FG
            /// </summary>
            [EnumMember(Value = "FG")]
            FGEnum = 77,
            /// <summary>
            /// Enum FJEnum for FJ
            /// </summary>
            [EnumMember(Value = "FJ")]
            FJEnum = 78,
            /// <summary>
            /// Enum FNEnum for FN
            /// </summary>
            [EnumMember(Value = "FN")]
            FNEnum = 79,
            /// <summary>
            /// Enum FPEnum for FP
            /// </summary>
            [EnumMember(Value = "FP")]
            FPEnum = 80,
            /// <summary>
            /// Enum FREnum for FR
            /// </summary>
            [EnumMember(Value = "FR")]
            FREnum = 81,
            /// <summary>
            /// Enum FSEnum for FS
            /// </summary>
            [EnumMember(Value = "FS")]
            FSEnum = 82,
            /// <summary>
            /// Enum G0Enum for G0
            /// </summary>
            [EnumMember(Value = "G0")]
            G0Enum = 83,
            /// <summary>
            /// Enum GBEnum for GB
            /// </summary>
            [EnumMember(Value = "GB")]
            GBEnum = 84,
            /// <summary>
            /// Enum GCEnum for GC
            /// </summary>
            [EnumMember(Value = "GC")]
            GCEnum = 85,
            /// <summary>
            /// Enum GDEnum for GD
            /// </summary>
            [EnumMember(Value = "GD")]
            GDEnum = 86,
            /// <summary>
            /// Enum GEEnum for GE
            /// </summary>
            [EnumMember(Value = "GE")]
            GEEnum = 87,
            /// <summary>
            /// Enum GFEnum for GF
            /// </summary>
            [EnumMember(Value = "GF")]
            GFEnum = 88,
            /// <summary>
            /// Enum GGEnum for GG
            /// </summary>
            [EnumMember(Value = "GG")]
            GGEnum = 89,
            /// <summary>
            /// Enum GIEnum for GI
            /// </summary>
            [EnumMember(Value = "GI")]
            GIEnum = 90,
            /// <summary>
            /// Enum GJEnum for GJ
            /// </summary>
            [EnumMember(Value = "GJ")]
            GJEnum = 91,
            /// <summary>
            /// Enum GKEnum for GK
            /// </summary>
            [EnumMember(Value = "GK")]
            GKEnum = 92,
            /// <summary>
            /// Enum GNEnum for GN
            /// </summary>
            [EnumMember(Value = "GN")]
            GNEnum = 93,
            /// <summary>
            /// Enum GPEnum for GP
            /// </summary>
            [EnumMember(Value = "GP")]
            GPEnum = 94,
            /// <summary>
            /// Enum GSEnum for GS
            /// </summary>
            [EnumMember(Value = "GS")]
            GSEnum = 95,
            /// <summary>
            /// Enum GTEnum for GT
            /// </summary>
            [EnumMember(Value = "GT")]
            GTEnum = 96,
            /// <summary>
            /// Enum GYEnum for GY
            /// </summary>
            [EnumMember(Value = "GY")]
            GYEnum = 97,
            /// <summary>
            /// Enum GZEnum for GZ
            /// </summary>
            [EnumMember(Value = "GZ")]
            GZEnum = 98,
            /// <summary>
            /// Enum HCEnum for HC
            /// </summary>
            [EnumMember(Value = "HC")]
            HCEnum = 99,
            /// <summary>
            /// Enum HDEnum for HD
            /// </summary>
            [EnumMember(Value = "HD")]
            HDEnum = 100,
            /// <summary>
            /// Enum HEEnum for HE
            /// </summary>
            [EnumMember(Value = "HE")]
            HEEnum = 101,
            /// <summary>
            /// Enum HKEnum for HK
            /// </summary>
            [EnumMember(Value = "HK")]
            HKEnum = 102,
            /// <summary>
            /// Enum HNEnum for HN
            /// </summary>
            [EnumMember(Value = "HN")]
            HNEnum = 103,
            /// <summary>
            /// Enum HREnum for HR
            /// </summary>
            [EnumMember(Value = "HR")]
            HREnum = 104,
            /// <summary>
            /// Enum HSEnum for HS
            /// </summary>
            [EnumMember(Value = "HS")]
            HSEnum = 105,
            /// <summary>
            /// Enum HTEnum for HT
            /// </summary>
            [EnumMember(Value = "HT")]
            HTEnum = 106,
            /// <summary>
            /// Enum HUEnum for HU
            /// </summary>
            [EnumMember(Value = "HU")]
            HUEnum = 107,
            /// <summary>
            /// Enum I0Enum for I0
            /// </summary>
            [EnumMember(Value = "I0")]
            I0Enum = 108,
            /// <summary>
            /// Enum IBEnum for IB
            /// </summary>
            [EnumMember(Value = "IB")]
            IBEnum = 109,
            /// <summary>
            /// Enum ICEnum for IC
            /// </summary>
            [EnumMember(Value = "IC")]
            ICEnum = 110,
            /// <summary>
            /// Enum IEEnum for IE
            /// </summary>
            [EnumMember(Value = "IE")]
            IEEnum = 111,
            /// <summary>
            /// Enum IIEnum for II
            /// </summary>
            [EnumMember(Value = "II")]
            IIEnum = 112,
            /// <summary>
            /// Enum IMEnum for IM
            /// </summary>
            [EnumMember(Value = "IM")]
            IMEnum = 113,
            /// <summary>
            /// Enum IQEnum for IQ
            /// </summary>
            [EnumMember(Value = "IQ")]
            IQEnum = 114,
            /// <summary>
            /// Enum IREnum for IR
            /// </summary>
            [EnumMember(Value = "IR")]
            IREnum = 115,
            /// <summary>
            /// Enum ISEnum for IS
            /// </summary>
            [EnumMember(Value = "IS")]
            ISEnum = 116,
            /// <summary>
            /// Enum ITEnum for IT
            /// </summary>
            [EnumMember(Value = "IT")]
            ITEnum = 117,
            /// <summary>
            /// Enum IUEnum for IU
            /// </summary>
            [EnumMember(Value = "IU")]
            IUEnum = 118,
            /// <summary>
            /// Enum IYEnum for IY
            /// </summary>
            [EnumMember(Value = "IY")]
            IYEnum = 119,
            /// <summary>
            /// Enum J0Enum for J0
            /// </summary>
            [EnumMember(Value = "J0")]
            J0Enum = 120,
            /// <summary>
            /// Enum JAEnum for JA
            /// </summary>
            [EnumMember(Value = "JA")]
            JAEnum = 121,
            /// <summary>
            /// Enum JEEnum for JE
            /// </summary>
            [EnumMember(Value = "JE")]
            JEEnum = 122,
            /// <summary>
            /// Enum JMEnum for JM
            /// </summary>
            [EnumMember(Value = "JM")]
            JMEnum = 123,
            /// <summary>
            /// Enum JNEnum for JN
            /// </summary>
            [EnumMember(Value = "JN")]
            JNEnum = 124,
            /// <summary>
            /// Enum JUEnum for JU
            /// </summary>
            [EnumMember(Value = "JU")]
            JUEnum = 125,
            /// <summary>
            /// Enum K0Enum for K0
            /// </summary>
            [EnumMember(Value = "K0")]
            K0Enum = 126,
            /// <summary>
            /// Enum KBEnum for KB
            /// </summary>
            [EnumMember(Value = "KB")]
            KBEnum = 127,
            /// <summary>
            /// Enum KCEnum for KC
            /// </summary>
            [EnumMember(Value = "KC")]
            KCEnum = 128,
            /// <summary>
            /// Enum KEEnum for KE
            /// </summary>
            [EnumMember(Value = "KE")]
            KEEnum = 129,
            /// <summary>
            /// Enum KHEnum for KH
            /// </summary>
            [EnumMember(Value = "KH")]
            KHEnum = 130,
            /// <summary>
            /// Enum KNEnum for KN
            /// </summary>
            [EnumMember(Value = "KN")]
            KNEnum = 131,
            /// <summary>
            /// Enum KTEnum for KT
            /// </summary>
            [EnumMember(Value = "KT")]
            KTEnum = 132,
            /// <summary>
            /// Enum KUEnum for KU
            /// </summary>
            [EnumMember(Value = "KU")]
            KUEnum = 133,
            /// <summary>
            /// Enum KVEnum for KV
            /// </summary>
            [EnumMember(Value = "KV")]
            KVEnum = 134,
            /// <summary>
            /// Enum KZEnum for KZ
            /// </summary>
            [EnumMember(Value = "KZ")]
            KZEnum = 135,
            /// <summary>
            /// Enum L0Enum for L0
            /// </summary>
            [EnumMember(Value = "L0")]
            L0Enum = 136,
            /// <summary>
            /// Enum LBEnum for LB
            /// </summary>
            [EnumMember(Value = "LB")]
            LBEnum = 137,
            /// <summary>
            /// Enum LDEnum for LD
            /// </summary>
            [EnumMember(Value = "LD")]
            LDEnum = 138,
            /// <summary>
            /// Enum LEEnum for LE
            /// </summary>
            [EnumMember(Value = "LE")]
            LEEnum = 139,
            /// <summary>
            /// Enum LFEnum for LF
            /// </summary>
            [EnumMember(Value = "LF")]
            LFEnum = 140,
            /// <summary>
            /// Enum LHEnum for LH
            /// </summary>
            [EnumMember(Value = "LH")]
            LHEnum = 141,
            /// <summary>
            /// Enum LIEnum for LI
            /// </summary>
            [EnumMember(Value = "LI")]
            LIEnum = 142,
            /// <summary>
            /// Enum LNEnum for LN
            /// </summary>
            [EnumMember(Value = "LN")]
            LNEnum = 143,
            /// <summary>
            /// Enum LSEnum for LS
            /// </summary>
            [EnumMember(Value = "LS")]
            LSEnum = 144,
            /// <summary>
            /// Enum LTEnum for LT
            /// </summary>
            [EnumMember(Value = "LT")]
            LTEnum = 145,
            /// <summary>
            /// Enum LUEnum for LU
            /// </summary>
            [EnumMember(Value = "LU")]
            LUEnum = 146,
            /// <summary>
            /// Enum LXEnum for LX
            /// </summary>
            [EnumMember(Value = "LX")]
            LXEnum = 147,
            /// <summary>
            /// Enum LYEnum for LY
            /// </summary>
            [EnumMember(Value = "LY")]
            LYEnum = 148,
            /// <summary>
            /// Enum MFEnum for MF
            /// </summary>
            [EnumMember(Value = "MF")]
            MFEnum = 149,
            /// <summary>
            /// Enum MGEnum for MG
            /// </summary>
            [EnumMember(Value = "MG")]
            MGEnum = 150,
            /// <summary>
            /// Enum MJEnum for MJ
            /// </summary>
            [EnumMember(Value = "MJ")]
            MJEnum = 151,
            /// <summary>
            /// Enum MLEnum for ML
            /// </summary>
            [EnumMember(Value = "ML")]
            MLEnum = 152,
            /// <summary>
            /// Enum MMEnum for MM
            /// </summary>
            [EnumMember(Value = "MM")]
            MMEnum = 153,
            /// <summary>
            /// Enum MPEnum for MP
            /// </summary>
            [EnumMember(Value = "MP")]
            MPEnum = 154,
            /// <summary>
            /// Enum MQEnum for MQ
            /// </summary>
            [EnumMember(Value = "MQ")]
            MQEnum = 155,
            /// <summary>
            /// Enum MUEnum for MU
            /// </summary>
            [EnumMember(Value = "MU")]
            MUEnum = 156,
            /// <summary>
            /// Enum MVEnum for MV
            /// </summary>
            [EnumMember(Value = "MV")]
            MVEnum = 157,
            /// <summary>
            /// Enum MYEnum for MY
            /// </summary>
            [EnumMember(Value = "MY")]
            MYEnum = 158,
            /// <summary>
            /// Enum MZEnum for MZ
            /// </summary>
            [EnumMember(Value = "MZ")]
            MZEnum = 159,
            /// <summary>
            /// Enum N0Enum for N0
            /// </summary>
            [EnumMember(Value = "N0")]
            N0Enum = 160,
            /// <summary>
            /// Enum NEEnum for NE
            /// </summary>
            [EnumMember(Value = "NE")]
            NEEnum = 161,
            /// <summary>
            /// Enum NGEnum for NG
            /// </summary>
            [EnumMember(Value = "NG")]
            NGEnum = 162,
            /// <summary>
            /// Enum NIEnum for NI
            /// </summary>
            [EnumMember(Value = "NI")]
            NIEnum = 163,
            /// <summary>
            /// Enum NNEnum for NN
            /// </summary>
            [EnumMember(Value = "NN")]
            NNEnum = 164,
            /// <summary>
            /// Enum NPEnum for NP
            /// </summary>
            [EnumMember(Value = "NP")]
            NPEnum = 165,
            /// <summary>
            /// Enum NQEnum for NQ
            /// </summary>
            [EnumMember(Value = "NQ")]
            NQEnum = 166,
            /// <summary>
            /// Enum NREnum for NR
            /// </summary>
            [EnumMember(Value = "NR")]
            NREnum = 167,
            /// <summary>
            /// Enum NUEnum for NU
            /// </summary>
            [EnumMember(Value = "NU")]
            NUEnum = 168,
            /// <summary>
            /// Enum NWEnum for NW
            /// </summary>
            [EnumMember(Value = "NW")]
            NWEnum = 169,
            /// <summary>
            /// Enum NXEnum for NX
            /// </summary>
            [EnumMember(Value = "NX")]
            NXEnum = 170,
            /// <summary>
            /// Enum NZEnum for NZ
            /// </summary>
            [EnumMember(Value = "NZ")]
            NZEnum = 171,
            /// <summary>
            /// Enum P0Enum for P0
            /// </summary>
            [EnumMember(Value = "P0")]
            P0Enum = 172,
            /// <summary>
            /// Enum PCEnum for PC
            /// </summary>
            [EnumMember(Value = "PC")]
            PCEnum = 173,
            /// <summary>
            /// Enum PDEnum for PD
            /// </summary>
            [EnumMember(Value = "PD")]
            PDEnum = 174,
            /// <summary>
            /// Enum PFEnum for PF
            /// </summary>
            [EnumMember(Value = "PF")]
            PFEnum = 175,
            /// <summary>
            /// Enum PGEnum for PG
            /// </summary>
            [EnumMember(Value = "PG")]
            PGEnum = 176,
            /// <summary>
            /// Enum PIEnum for PI
            /// </summary>
            [EnumMember(Value = "PI")]
            PIEnum = 177,
            /// <summary>
            /// Enum PKEnum for PK
            /// </summary>
            [EnumMember(Value = "PK")]
            PKEnum = 178,
            /// <summary>
            /// Enum PMEnum for PM
            /// </summary>
            [EnumMember(Value = "PM")]
            PMEnum = 179,
            /// <summary>
            /// Enum PSEnum for PS
            /// </summary>
            [EnumMember(Value = "PS")]
            PSEnum = 180,
            /// <summary>
            /// Enum PTEnum for PT
            /// </summary>
            [EnumMember(Value = "PT")]
            PTEnum = 181,
            /// <summary>
            /// Enum PUEnum for PU
            /// </summary>
            [EnumMember(Value = "PU")]
            PUEnum = 182,
            /// <summary>
            /// Enum PVEnum for PV
            /// </summary>
            [EnumMember(Value = "PV")]
            PVEnum = 183,
            /// <summary>
            /// Enum QAEnum for QA
            /// </summary>
            [EnumMember(Value = "QA")]
            QAEnum = 184,
            /// <summary>
            /// Enum RAEnum for RA
            /// </summary>
            [EnumMember(Value = "RA")]
            RAEnum = 185,
            /// <summary>
            /// Enum RBEnum for RB
            /// </summary>
            [EnumMember(Value = "RB")]
            RBEnum = 186,
            /// <summary>
            /// Enum RCEnum for RC
            /// </summary>
            [EnumMember(Value = "RC")]
            RCEnum = 187,
            /// <summary>
            /// Enum REEnum for RE
            /// </summary>
            [EnumMember(Value = "RE")]
            REEnum = 188,
            /// <summary>
            /// Enum RFEnum for RF
            /// </summary>
            [EnumMember(Value = "RF")]
            RFEnum = 189,
            /// <summary>
            /// Enum RGEnum for RG
            /// </summary>
            [EnumMember(Value = "RG")]
            RGEnum = 190,
            /// <summary>
            /// Enum RHEnum for RH
            /// </summary>
            [EnumMember(Value = "RH")]
            RHEnum = 191,
            /// <summary>
            /// Enum RREnum for RR
            /// </summary>
            [EnumMember(Value = "RR")]
            RREnum = 192,
            /// <summary>
            /// Enum RSEnum for RS
            /// </summary>
            [EnumMember(Value = "RS")]
            RSEnum = 193,
            /// <summary>
            /// Enum RUEnum for RU
            /// </summary>
            [EnumMember(Value = "RU")]
            RUEnum = 194,
            /// <summary>
            /// Enum RVEnum for RV
            /// </summary>
            [EnumMember(Value = "RV")]
            RVEnum = 195,
            /// <summary>
            /// Enum RWEnum for RW
            /// </summary>
            [EnumMember(Value = "RW")]
            RWEnum = 196,
            /// <summary>
            /// Enum RYEnum for RY
            /// </summary>
            [EnumMember(Value = "RY")]
            RYEnum = 197,
            /// <summary>
            /// Enum SAEnum for SA
            /// </summary>
            [EnumMember(Value = "SA")]
            SAEnum = 198,
            /// <summary>
            /// Enum SBEnum for SB
            /// </summary>
            [EnumMember(Value = "SB")]
            SBEnum = 199,
            /// <summary>
            /// Enum SEEnum for SE
            /// </summary>
            [EnumMember(Value = "SE")]
            SEEnum = 200,
            /// <summary>
            /// Enum SFEnum for SF
            /// </summary>
            [EnumMember(Value = "SF")]
            SFEnum = 201,
            /// <summary>
            /// Enum SGEnum for SG
            /// </summary>
            [EnumMember(Value = "SG")]
            SGEnum = 202,
            /// <summary>
            /// Enum SHEnum for SH
            /// </summary>
            [EnumMember(Value = "SH")]
            SHEnum = 203,
            /// <summary>
            /// Enum SJEnum for SJ
            /// </summary>
            [EnumMember(Value = "SJ")]
            SJEnum = 204,
            /// <summary>
            /// Enum SMEnum for SM
            /// </summary>
            [EnumMember(Value = "SM")]
            SMEnum = 205,
            /// <summary>
            /// Enum SPEnum for SP
            /// </summary>
            [EnumMember(Value = "SP")]
            SPEnum = 206,
            /// <summary>
            /// Enum SQEnum for SQ
            /// </summary>
            [EnumMember(Value = "SQ")]
            SQEnum = 207,
            /// <summary>
            /// Enum SREnum for SR
            /// </summary>
            [EnumMember(Value = "SR")]
            SREnum = 208,
            /// <summary>
            /// Enum SSEnum for SS
            /// </summary>
            [EnumMember(Value = "SS")]
            SSEnum = 209,
            /// <summary>
            /// Enum SUEnum for SU
            /// </summary>
            [EnumMember(Value = "SU")]
            SUEnum = 210,
            /// <summary>
            /// Enum SVEnum for SV
            /// </summary>
            [EnumMember(Value = "SV")]
            SVEnum = 211,
            /// <summary>
            /// Enum SWEnum for SW
            /// </summary>
            [EnumMember(Value = "SW")]
            SWEnum = 212,
            /// <summary>
            /// Enum SYEnum for SY
            /// </summary>
            [EnumMember(Value = "SY")]
            SYEnum = 213,
            /// <summary>
            /// Enum SZEnum for SZ
            /// </summary>
            [EnumMember(Value = "SZ")]
            SZEnum = 214,
            /// <summary>
            /// Enum T0Enum for T0
            /// </summary>
            [EnumMember(Value = "T0")]
            T0Enum = 215,
            /// <summary>
            /// Enum TCEnum for TC
            /// </summary>
            [EnumMember(Value = "TC")]
            TCEnum = 216,
            /// <summary>
            /// Enum TDEnum for TD
            /// </summary>
            [EnumMember(Value = "TD")]
            TDEnum = 217,
            /// <summary>
            /// Enum TEEnum for TE
            /// </summary>
            [EnumMember(Value = "TE")]
            TEEnum = 218,
            /// <summary>
            /// Enum TFEnum for TF
            /// </summary>
            [EnumMember(Value = "TF")]
            TFEnum = 219,
            /// <summary>
            /// Enum TGEnum for TG
            /// </summary>
            [EnumMember(Value = "TG")]
            TGEnum = 220,
            /// <summary>
            /// Enum THEnum for TH
            /// </summary>
            [EnumMember(Value = "TH")]
            THEnum = 221,
            /// <summary>
            /// Enum TJEnum for TJ
            /// </summary>
            [EnumMember(Value = "TJ")]
            TJEnum = 222,
            /// <summary>
            /// Enum TKEnum for TK
            /// </summary>
            [EnumMember(Value = "TK")]
            TKEnum = 223,
            /// <summary>
            /// Enum TMEnum for TM
            /// </summary>
            [EnumMember(Value = "TM")]
            TMEnum = 224,
            /// <summary>
            /// Enum TPEnum for TP
            /// </summary>
            [EnumMember(Value = "TP")]
            TPEnum = 225,
            /// <summary>
            /// Enum TQEnum for TQ
            /// </summary>
            [EnumMember(Value = "TQ")]
            TQEnum = 226,
            /// <summary>
            /// Enum TREnum for TR
            /// </summary>
            [EnumMember(Value = "TR")]
            TREnum = 227,
            /// <summary>
            /// Enum TSEnum for TS
            /// </summary>
            [EnumMember(Value = "TS")]
            TSEnum = 228,
            /// <summary>
            /// Enum TTEnum for TT
            /// </summary>
            [EnumMember(Value = "TT")]
            TTEnum = 229,
            /// <summary>
            /// Enum TUEnum for TU
            /// </summary>
            [EnumMember(Value = "TU")]
            TUEnum = 230,
            /// <summary>
            /// Enum TVEnum for TV
            /// </summary>
            [EnumMember(Value = "TV")]
            TVEnum = 231,
            /// <summary>
            /// Enum TWEnum for TW
            /// </summary>
            [EnumMember(Value = "TW")]
            TWEnum = 232,
            /// <summary>
            /// Enum TYEnum for TY
            /// </summary>
            [EnumMember(Value = "TY")]
            TYEnum = 233,
            /// <summary>
            /// Enum TZEnum for TZ
            /// </summary>
            [EnumMember(Value = "TZ")]
            TZEnum = 234,
            /// <summary>
            /// Enum UGEnum for UG
            /// </summary>
            [EnumMember(Value = "UG")]
            UGEnum = 235,
            /// <summary>
            /// Enum UKEnum for UK
            /// </summary>
            [EnumMember(Value = "UK")]
            UKEnum = 236,
            /// <summary>
            /// Enum UMEnum for UM
            /// </summary>
            [EnumMember(Value = "UM")]
            UMEnum = 237,
            /// <summary>
            /// Enum UNEnum for UN
            /// </summary>
            [EnumMember(Value = "UN")]
            UNEnum = 238,
            /// <summary>
            /// Enum UREnum for UR
            /// </summary>
            [EnumMember(Value = "UR")]
            UREnum = 239,
            /// <summary>
            /// Enum USEnum for US
            /// </summary>
            [EnumMember(Value = "US")]
            USEnum = 240,
            /// <summary>
            /// Enum UVEnum for UV
            /// </summary>
            [EnumMember(Value = "UV")]
            UVEnum = 241,
            /// <summary>
            /// Enum UYEnum for UY
            /// </summary>
            [EnumMember(Value = "UY")]
            UYEnum = 242,
            /// <summary>
            /// Enum UZEnum for UZ
            /// </summary>
            [EnumMember(Value = "UZ")]
            UZEnum = 243,
            /// <summary>
            /// Enum VBEnum for VB
            /// </summary>
            [EnumMember(Value = "VB")]
            VBEnum = 244,
            /// <summary>
            /// Enum VVEnum for VV
            /// </summary>
            [EnumMember(Value = "VV")]
            VVEnum = 245,
            /// <summary>
            /// Enum VYEnum for VY
            /// </summary>
            [EnumMember(Value = "VY")]
            VYEnum = 246,
            /// <summary>
            /// Enum VZEnum for VZ
            /// </summary>
            [EnumMember(Value = "VZ")]
            VZEnum = 247,
            /// <summary>
            /// Enum WBEnum for WB
            /// </summary>
            [EnumMember(Value = "WB")]
            WBEnum = 248,
            /// <summary>
            /// Enum WFEnum for WF
            /// </summary>
            [EnumMember(Value = "WF")]
            WFEnum = 249,
            /// <summary>
            /// Enum WLEnum for WL
            /// </summary>
            [EnumMember(Value = "WL")]
            WLEnum = 250,
            /// <summary>
            /// Enum WNEnum for WN
            /// </summary>
            [EnumMember(Value = "WN")]
            WNEnum = 251,
            /// <summary>
            /// Enum WSEnum for WS
            /// </summary>
            [EnumMember(Value = "WS")]
            WSEnum = 252,
            /// <summary>
            /// Enum XAEnum for XA
            /// </summary>
            [EnumMember(Value = "XA")]
            XAEnum = 253,
            /// <summary>
            /// Enum XBEnum for XB
            /// </summary>
            [EnumMember(Value = "XB")]
            XBEnum = 254,
            /// <summary>
            /// Enum XXEnum for XX
            /// </summary>
            [EnumMember(Value = "XX")]
            XXEnum = 255,
            /// <summary>
            /// Enum Y0Enum for Y0
            /// </summary>
            [EnumMember(Value = "Y0")]
            Y0Enum = 256,
            /// <summary>
            /// Enum YGEnum for YG
            /// </summary>
            [EnumMember(Value = "YG")]
            YGEnum = 257,
            /// <summary>
            /// Enum YYEnum for YY
            /// </summary>
            [EnumMember(Value = "YY")]
            YYEnum = 258,
            /// <summary>
            /// Enum Z0Enum for Z0
            /// </summary>
            [EnumMember(Value = "Z0")]
            Z0Enum = 259,
            /// <summary>
            /// Enum ZBEnum for ZB
            /// </summary>
            [EnumMember(Value = "ZB")]
            ZBEnum = 260,
            /// <summary>
            /// Enum ZCEnum for ZC
            /// </summary>
            [EnumMember(Value = "ZC")]
            ZCEnum = 261,
            /// <summary>
            /// Enum ZDEnum for ZD
            /// </summary>
            [EnumMember(Value = "ZD")]
            ZDEnum = 262,
            /// <summary>
            /// Enum ZFEnum for ZF
            /// </summary>
            [EnumMember(Value = "ZF")]
            ZFEnum = 263,
            /// <summary>
            /// Enum ZIEnum for ZI
            /// </summary>
            [EnumMember(Value = "ZI")]
            ZIEnum = 264,
            /// <summary>
            /// Enum ZMEnum for ZM
            /// </summary>
            [EnumMember(Value = "ZM")]
            ZMEnum = 265,
            /// <summary>
            /// Enum ZREnum for ZR
            /// </summary>
            [EnumMember(Value = "ZR")]
            ZREnum = 266        }
}
