/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for 3 - Uniform Offense Classification (OFF, OOC, and CRR) Field Codes
        /// </summary>
        /// <value>A data type for 3 - Uniform Offense Classification (OFF, OOC, and CRR) Field Codes</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NcicOFFCodeSimpleType
        {
            /// <summary>
            /// Enum NUMBER_0101 for 0101
            /// </summary>
            [EnumMember(Value = "0101")]
            NUMBER_0101 = 0,
            /// <summary>
            /// Enum NUMBER_0102 for 0102
            /// </summary>
            [EnumMember(Value = "0102")]
            NUMBER_0102 = 1,
            /// <summary>
            /// Enum NUMBER_0103 for 0103
            /// </summary>
            [EnumMember(Value = "0103")]
            NUMBER_0103 = 2,
            /// <summary>
            /// Enum NUMBER_0104 for 0104
            /// </summary>
            [EnumMember(Value = "0104")]
            NUMBER_0104 = 3,
            /// <summary>
            /// Enum NUMBER_0105 for 0105
            /// </summary>
            [EnumMember(Value = "0105")]
            NUMBER_0105 = 4,
            /// <summary>
            /// Enum NUMBER_0106 for 0106
            /// </summary>
            [EnumMember(Value = "0106")]
            NUMBER_0106 = 5,
            /// <summary>
            /// Enum NUMBER_199 for 199
            /// </summary>
            [EnumMember(Value = "199")]
            NUMBER_199 = 6,
            /// <summary>
            /// Enum NUMBER_0201 for 0201
            /// </summary>
            [EnumMember(Value = "0201")]
            NUMBER_0201 = 7,
            /// <summary>
            /// Enum NUMBER_299 for 299
            /// </summary>
            [EnumMember(Value = "299")]
            NUMBER_299 = 8,
            /// <summary>
            /// Enum NUMBER_0301 for 0301
            /// </summary>
            [EnumMember(Value = "0301")]
            NUMBER_0301 = 9,
            /// <summary>
            /// Enum NUMBER_0302 for 0302
            /// </summary>
            [EnumMember(Value = "0302")]
            NUMBER_0302 = 10,
            /// <summary>
            /// Enum NUMBER_0303 for 0303
            /// </summary>
            [EnumMember(Value = "0303")]
            NUMBER_0303 = 11,
            /// <summary>
            /// Enum NUMBER_399 for 399
            /// </summary>
            [EnumMember(Value = "399")]
            NUMBER_399 = 12,
            /// <summary>
            /// Enum NUMBER_901 for 901
            /// </summary>
            [EnumMember(Value = "901")]
            NUMBER_901 = 13,
            /// <summary>
            /// Enum NUMBER_902 for 902
            /// </summary>
            [EnumMember(Value = "902")]
            NUMBER_902 = 14,
            /// <summary>
            /// Enum NUMBER_903 for 903
            /// </summary>
            [EnumMember(Value = "903")]
            NUMBER_903 = 15,
            /// <summary>
            /// Enum NUMBER_904 for 904
            /// </summary>
            [EnumMember(Value = "904")]
            NUMBER_904 = 16,
            /// <summary>
            /// Enum NUMBER_905 for 905
            /// </summary>
            [EnumMember(Value = "905")]
            NUMBER_905 = 17,
            /// <summary>
            /// Enum NUMBER_906 for 906
            /// </summary>
            [EnumMember(Value = "906")]
            NUMBER_906 = 18,
            /// <summary>
            /// Enum NUMBER_907 for 907
            /// </summary>
            [EnumMember(Value = "907")]
            NUMBER_907 = 19,
            /// <summary>
            /// Enum NUMBER_908 for 908
            /// </summary>
            [EnumMember(Value = "908")]
            NUMBER_908 = 20,
            /// <summary>
            /// Enum NUMBER_909 for 909
            /// </summary>
            [EnumMember(Value = "909")]
            NUMBER_909 = 21,
            /// <summary>
            /// Enum NUMBER_910 for 910
            /// </summary>
            [EnumMember(Value = "910")]
            NUMBER_910 = 22,
            /// <summary>
            /// Enum NUMBER_911 for 911
            /// </summary>
            [EnumMember(Value = "911")]
            NUMBER_911 = 23,
            /// <summary>
            /// Enum NUMBER_912 for 912
            /// </summary>
            [EnumMember(Value = "912")]
            NUMBER_912 = 24,
            /// <summary>
            /// Enum NUMBER_913 for 913
            /// </summary>
            [EnumMember(Value = "913")]
            NUMBER_913 = 25,
            /// <summary>
            /// Enum NUMBER_999 for 999
            /// </summary>
            [EnumMember(Value = "999")]
            NUMBER_999 = 26,
            /// <summary>
            /// Enum NUMBER_1001 for 1001
            /// </summary>
            [EnumMember(Value = "1001")]
            NUMBER_1001 = 27,
            /// <summary>
            /// Enum NUMBER_1002 for 1002
            /// </summary>
            [EnumMember(Value = "1002")]
            NUMBER_1002 = 28,
            /// <summary>
            /// Enum NUMBER_1003 for 1003
            /// </summary>
            [EnumMember(Value = "1003")]
            NUMBER_1003 = 29,
            /// <summary>
            /// Enum NUMBER_1004 for 1004
            /// </summary>
            [EnumMember(Value = "1004")]
            NUMBER_1004 = 30,
            /// <summary>
            /// Enum NUMBER_1005 for 1005
            /// </summary>
            [EnumMember(Value = "1005")]
            NUMBER_1005 = 31,
            /// <summary>
            /// Enum NUMBER_1006 for 1006
            /// </summary>
            [EnumMember(Value = "1006")]
            NUMBER_1006 = 32,
            /// <summary>
            /// Enum NUMBER_1007 for 1007
            /// </summary>
            [EnumMember(Value = "1007")]
            NUMBER_1007 = 33,
            /// <summary>
            /// Enum NUMBER_1008 for 1008
            /// </summary>
            [EnumMember(Value = "1008")]
            NUMBER_1008 = 34,
            /// <summary>
            /// Enum NUMBER_1009 for 1009
            /// </summary>
            [EnumMember(Value = "1009")]
            NUMBER_1009 = 35,
            /// <summary>
            /// Enum NUMBER_1010 for 1010
            /// </summary>
            [EnumMember(Value = "1010")]
            NUMBER_1010 = 36,
            /// <summary>
            /// Enum NUMBER_1011 for 1011
            /// </summary>
            [EnumMember(Value = "1011")]
            NUMBER_1011 = 37,
            /// <summary>
            /// Enum NUMBER_1020 for 1020
            /// </summary>
            [EnumMember(Value = "1020")]
            NUMBER_1020 = 38,
            /// <summary>
            /// Enum NUMBER_1021 for 1021
            /// </summary>
            [EnumMember(Value = "1021")]
            NUMBER_1021 = 39,
            /// <summary>
            /// Enum NUMBER_1099 for 1099
            /// </summary>
            [EnumMember(Value = "1099")]
            NUMBER_1099 = 40,
            /// <summary>
            /// Enum NUMBER_1101 for 1101
            /// </summary>
            [EnumMember(Value = "1101")]
            NUMBER_1101 = 41,
            /// <summary>
            /// Enum NUMBER_1102 for 1102
            /// </summary>
            [EnumMember(Value = "1102")]
            NUMBER_1102 = 42,
            /// <summary>
            /// Enum NUMBER_1103 for 1103
            /// </summary>
            [EnumMember(Value = "1103")]
            NUMBER_1103 = 43,
            /// <summary>
            /// Enum NUMBER_1104 for 1104
            /// </summary>
            [EnumMember(Value = "1104")]
            NUMBER_1104 = 44,
            /// <summary>
            /// Enum NUMBER_1105 for 1105
            /// </summary>
            [EnumMember(Value = "1105")]
            NUMBER_1105 = 45,
            /// <summary>
            /// Enum NUMBER_1106 for 1106
            /// </summary>
            [EnumMember(Value = "1106")]
            NUMBER_1106 = 46,
            /// <summary>
            /// Enum NUMBER_1107 for 1107
            /// </summary>
            [EnumMember(Value = "1107")]
            NUMBER_1107 = 47,
            /// <summary>
            /// Enum NUMBER_1108 for 1108
            /// </summary>
            [EnumMember(Value = "1108")]
            NUMBER_1108 = 48,
            /// <summary>
            /// Enum NUMBER_1109 for 1109
            /// </summary>
            [EnumMember(Value = "1109")]
            NUMBER_1109 = 49,
            /// <summary>
            /// Enum NUMBER_1110 for 1110
            /// </summary>
            [EnumMember(Value = "1110")]
            NUMBER_1110 = 50,
            /// <summary>
            /// Enum NUMBER_1111 for 1111
            /// </summary>
            [EnumMember(Value = "1111")]
            NUMBER_1111 = 51,
            /// <summary>
            /// Enum NUMBER_1112 for 1112
            /// </summary>
            [EnumMember(Value = "1112")]
            NUMBER_1112 = 52,
            /// <summary>
            /// Enum NUMBER_1113 for 1113
            /// </summary>
            [EnumMember(Value = "1113")]
            NUMBER_1113 = 53,
            /// <summary>
            /// Enum NUMBER_1114 for 1114
            /// </summary>
            [EnumMember(Value = "1114")]
            NUMBER_1114 = 54,
            /// <summary>
            /// Enum NUMBER_1115 for 1115
            /// </summary>
            [EnumMember(Value = "1115")]
            NUMBER_1115 = 55,
            /// <summary>
            /// Enum NUMBER_1116 for 1116
            /// </summary>
            [EnumMember(Value = "1116")]
            NUMBER_1116 = 56,
            /// <summary>
            /// Enum NUMBER_1117 for 1117
            /// </summary>
            [EnumMember(Value = "1117")]
            NUMBER_1117 = 57,
            /// <summary>
            /// Enum NUMBER_1118 for 1118
            /// </summary>
            [EnumMember(Value = "1118")]
            NUMBER_1118 = 58,
            /// <summary>
            /// Enum NUMBER_1119 for 1119
            /// </summary>
            [EnumMember(Value = "1119")]
            NUMBER_1119 = 59,
            /// <summary>
            /// Enum NUMBER_1120 for 1120
            /// </summary>
            [EnumMember(Value = "1120")]
            NUMBER_1120 = 60,
            /// <summary>
            /// Enum NUMBER_1121 for 1121
            /// </summary>
            [EnumMember(Value = "1121")]
            NUMBER_1121 = 61,
            /// <summary>
            /// Enum NUMBER_1122 for 1122
            /// </summary>
            [EnumMember(Value = "1122")]
            NUMBER_1122 = 62,
            /// <summary>
            /// Enum NUMBER_1123 for 1123
            /// </summary>
            [EnumMember(Value = "1123")]
            NUMBER_1123 = 63,
            /// <summary>
            /// Enum NUMBER_1198 for 1198
            /// </summary>
            [EnumMember(Value = "1198")]
            NUMBER_1198 = 64,
            /// <summary>
            /// Enum NUMBER_1199 for 1199
            /// </summary>
            [EnumMember(Value = "1199")]
            NUMBER_1199 = 65,
            /// <summary>
            /// Enum NUMBER_1201 for 1201
            /// </summary>
            [EnumMember(Value = "1201")]
            NUMBER_1201 = 66,
            /// <summary>
            /// Enum NUMBER_1202 for 1202
            /// </summary>
            [EnumMember(Value = "1202")]
            NUMBER_1202 = 67,
            /// <summary>
            /// Enum NUMBER_1203 for 1203
            /// </summary>
            [EnumMember(Value = "1203")]
            NUMBER_1203 = 68,
            /// <summary>
            /// Enum NUMBER_1204 for 1204
            /// </summary>
            [EnumMember(Value = "1204")]
            NUMBER_1204 = 69,
            /// <summary>
            /// Enum NUMBER_1205 for 1205
            /// </summary>
            [EnumMember(Value = "1205")]
            NUMBER_1205 = 70,
            /// <summary>
            /// Enum NUMBER_1206 for 1206
            /// </summary>
            [EnumMember(Value = "1206")]
            NUMBER_1206 = 71,
            /// <summary>
            /// Enum NUMBER_1207 for 1207
            /// </summary>
            [EnumMember(Value = "1207")]
            NUMBER_1207 = 72,
            /// <summary>
            /// Enum NUMBER_1208 for 1208
            /// </summary>
            [EnumMember(Value = "1208")]
            NUMBER_1208 = 73,
            /// <summary>
            /// Enum NUMBER_1209 for 1209
            /// </summary>
            [EnumMember(Value = "1209")]
            NUMBER_1209 = 74,
            /// <summary>
            /// Enum NUMBER_1210 for 1210
            /// </summary>
            [EnumMember(Value = "1210")]
            NUMBER_1210 = 75,
            /// <summary>
            /// Enum NUMBER_1211 for 1211
            /// </summary>
            [EnumMember(Value = "1211")]
            NUMBER_1211 = 76,
            /// <summary>
            /// Enum NUMBER_1212 for 1212
            /// </summary>
            [EnumMember(Value = "1212")]
            NUMBER_1212 = 77,
            /// <summary>
            /// Enum NUMBER_1299 for 1299
            /// </summary>
            [EnumMember(Value = "1299")]
            NUMBER_1299 = 78,
            /// <summary>
            /// Enum NUMBER_1301 for 1301
            /// </summary>
            [EnumMember(Value = "1301")]
            NUMBER_1301 = 79,
            /// <summary>
            /// Enum NUMBER_1302 for 1302
            /// </summary>
            [EnumMember(Value = "1302")]
            NUMBER_1302 = 80,
            /// <summary>
            /// Enum NUMBER_1303 for 1303
            /// </summary>
            [EnumMember(Value = "1303")]
            NUMBER_1303 = 81,
            /// <summary>
            /// Enum NUMBER_1304 for 1304
            /// </summary>
            [EnumMember(Value = "1304")]
            NUMBER_1304 = 82,
            /// <summary>
            /// Enum NUMBER_1305 for 1305
            /// </summary>
            [EnumMember(Value = "1305")]
            NUMBER_1305 = 83,
            /// <summary>
            /// Enum NUMBER_1306 for 1306
            /// </summary>
            [EnumMember(Value = "1306")]
            NUMBER_1306 = 84,
            /// <summary>
            /// Enum NUMBER_1307 for 1307
            /// </summary>
            [EnumMember(Value = "1307")]
            NUMBER_1307 = 85,
            /// <summary>
            /// Enum NUMBER_1308 for 1308
            /// </summary>
            [EnumMember(Value = "1308")]
            NUMBER_1308 = 86,
            /// <summary>
            /// Enum NUMBER_1309 for 1309
            /// </summary>
            [EnumMember(Value = "1309")]
            NUMBER_1309 = 87,
            /// <summary>
            /// Enum NUMBER_1310 for 1310
            /// </summary>
            [EnumMember(Value = "1310")]
            NUMBER_1310 = 88,
            /// <summary>
            /// Enum NUMBER_1311 for 1311
            /// </summary>
            [EnumMember(Value = "1311")]
            NUMBER_1311 = 89,
            /// <summary>
            /// Enum NUMBER_1312 for 1312
            /// </summary>
            [EnumMember(Value = "1312")]
            NUMBER_1312 = 90,
            /// <summary>
            /// Enum NUMBER_1313 for 1313
            /// </summary>
            [EnumMember(Value = "1313")]
            NUMBER_1313 = 91,
            /// <summary>
            /// Enum NUMBER_1314 for 1314
            /// </summary>
            [EnumMember(Value = "1314")]
            NUMBER_1314 = 92,
            /// <summary>
            /// Enum NUMBER_1315 for 1315
            /// </summary>
            [EnumMember(Value = "1315")]
            NUMBER_1315 = 93,
            /// <summary>
            /// Enum NUMBER_1316 for 1316
            /// </summary>
            [EnumMember(Value = "1316")]
            NUMBER_1316 = 94,
            /// <summary>
            /// Enum NUMBER_1399 for 1399
            /// </summary>
            [EnumMember(Value = "1399")]
            NUMBER_1399 = 95,
            /// <summary>
            /// Enum NUMBER_1401 for 1401
            /// </summary>
            [EnumMember(Value = "1401")]
            NUMBER_1401 = 96,
            /// <summary>
            /// Enum NUMBER_1402 for 1402
            /// </summary>
            [EnumMember(Value = "1402")]
            NUMBER_1402 = 97,
            /// <summary>
            /// Enum NUMBER_1403 for 1403
            /// </summary>
            [EnumMember(Value = "1403")]
            NUMBER_1403 = 98,
            /// <summary>
            /// Enum NUMBER_1404 for 1404
            /// </summary>
            [EnumMember(Value = "1404")]
            NUMBER_1404 = 99,
            /// <summary>
            /// Enum NUMBER_1499 for 1499
            /// </summary>
            [EnumMember(Value = "1499")]
            NUMBER_1499 = 100,
            /// <summary>
            /// Enum NUMBER_1601 for 1601
            /// </summary>
            [EnumMember(Value = "1601")]
            NUMBER_1601 = 101,
            /// <summary>
            /// Enum NUMBER_1602 for 1602
            /// </summary>
            [EnumMember(Value = "1602")]
            NUMBER_1602 = 102,
            /// <summary>
            /// Enum NUMBER_1701 for 1701
            /// </summary>
            [EnumMember(Value = "1701")]
            NUMBER_1701 = 103,
            /// <summary>
            /// Enum NUMBER_1702 for 1702
            /// </summary>
            [EnumMember(Value = "1702")]
            NUMBER_1702 = 104,
            /// <summary>
            /// Enum NUMBER_2001 for 2001
            /// </summary>
            [EnumMember(Value = "2001")]
            NUMBER_2001 = 105,
            /// <summary>
            /// Enum NUMBER_2002 for 2002
            /// </summary>
            [EnumMember(Value = "2002")]
            NUMBER_2002 = 106,
            /// <summary>
            /// Enum NUMBER_2003 for 2003
            /// </summary>
            [EnumMember(Value = "2003")]
            NUMBER_2003 = 107,
            /// <summary>
            /// Enum NUMBER_2004 for 2004
            /// </summary>
            [EnumMember(Value = "2004")]
            NUMBER_2004 = 108,
            /// <summary>
            /// Enum NUMBER_2005 for 2005
            /// </summary>
            [EnumMember(Value = "2005")]
            NUMBER_2005 = 109,
            /// <summary>
            /// Enum NUMBER_2006 for 2006
            /// </summary>
            [EnumMember(Value = "2006")]
            NUMBER_2006 = 110,
            /// <summary>
            /// Enum NUMBER_2007 for 2007
            /// </summary>
            [EnumMember(Value = "2007")]
            NUMBER_2007 = 111,
            /// <summary>
            /// Enum NUMBER_2008 for 2008
            /// </summary>
            [EnumMember(Value = "2008")]
            NUMBER_2008 = 112,
            /// <summary>
            /// Enum NUMBER_2009 for 2009
            /// </summary>
            [EnumMember(Value = "2009")]
            NUMBER_2009 = 113,
            /// <summary>
            /// Enum NUMBER_2099 for 2099
            /// </summary>
            [EnumMember(Value = "2099")]
            NUMBER_2099 = 114,
            /// <summary>
            /// Enum NUMBER_2101 for 2101
            /// </summary>
            [EnumMember(Value = "2101")]
            NUMBER_2101 = 115,
            /// <summary>
            /// Enum NUMBER_2102 for 2102
            /// </summary>
            [EnumMember(Value = "2102")]
            NUMBER_2102 = 116,
            /// <summary>
            /// Enum NUMBER_2103 for 2103
            /// </summary>
            [EnumMember(Value = "2103")]
            NUMBER_2103 = 117,
            /// <summary>
            /// Enum NUMBER_2104 for 2104
            /// </summary>
            [EnumMember(Value = "2104")]
            NUMBER_2104 = 118,
            /// <summary>
            /// Enum NUMBER_2105 for 2105
            /// </summary>
            [EnumMember(Value = "2105")]
            NUMBER_2105 = 119,
            /// <summary>
            /// Enum NUMBER_2199 for 2199
            /// </summary>
            [EnumMember(Value = "2199")]
            NUMBER_2199 = 120,
            /// <summary>
            /// Enum NUMBER_2201 for 2201
            /// </summary>
            [EnumMember(Value = "2201")]
            NUMBER_2201 = 121,
            /// <summary>
            /// Enum NUMBER_2202 for 2202
            /// </summary>
            [EnumMember(Value = "2202")]
            NUMBER_2202 = 122,
            /// <summary>
            /// Enum NUMBER_2203 for 2203
            /// </summary>
            [EnumMember(Value = "2203")]
            NUMBER_2203 = 123,
            /// <summary>
            /// Enum NUMBER_2204 for 2204
            /// </summary>
            [EnumMember(Value = "2204")]
            NUMBER_2204 = 124,
            /// <summary>
            /// Enum NUMBER_2205 for 2205
            /// </summary>
            [EnumMember(Value = "2205")]
            NUMBER_2205 = 125,
            /// <summary>
            /// Enum NUMBER_2206 for 2206
            /// </summary>
            [EnumMember(Value = "2206")]
            NUMBER_2206 = 126,
            /// <summary>
            /// Enum NUMBER_2207 for 2207
            /// </summary>
            [EnumMember(Value = "2207")]
            NUMBER_2207 = 127,
            /// <summary>
            /// Enum NUMBER_2299 for 2299
            /// </summary>
            [EnumMember(Value = "2299")]
            NUMBER_2299 = 128,
            /// <summary>
            /// Enum NUMBER_2301 for 2301
            /// </summary>
            [EnumMember(Value = "2301")]
            NUMBER_2301 = 129,
            /// <summary>
            /// Enum NUMBER_2302 for 2302
            /// </summary>
            [EnumMember(Value = "2302")]
            NUMBER_2302 = 130,
            /// <summary>
            /// Enum NUMBER_2303 for 2303
            /// </summary>
            [EnumMember(Value = "2303")]
            NUMBER_2303 = 131,
            /// <summary>
            /// Enum NUMBER_2304 for 2304
            /// </summary>
            [EnumMember(Value = "2304")]
            NUMBER_2304 = 132,
            /// <summary>
            /// Enum NUMBER_2305 for 2305
            /// </summary>
            [EnumMember(Value = "2305")]
            NUMBER_2305 = 133,
            /// <summary>
            /// Enum NUMBER_2306 for 2306
            /// </summary>
            [EnumMember(Value = "2306")]
            NUMBER_2306 = 134,
            /// <summary>
            /// Enum NUMBER_2307 for 2307
            /// </summary>
            [EnumMember(Value = "2307")]
            NUMBER_2307 = 135,
            /// <summary>
            /// Enum NUMBER_2308 for 2308
            /// </summary>
            [EnumMember(Value = "2308")]
            NUMBER_2308 = 136,
            /// <summary>
            /// Enum NUMBER_2309 for 2309
            /// </summary>
            [EnumMember(Value = "2309")]
            NUMBER_2309 = 137,
            /// <summary>
            /// Enum NUMBER_2310 for 2310
            /// </summary>
            [EnumMember(Value = "2310")]
            NUMBER_2310 = 138,
            /// <summary>
            /// Enum NUMBER_2311 for 2311
            /// </summary>
            [EnumMember(Value = "2311")]
            NUMBER_2311 = 139,
            /// <summary>
            /// Enum NUMBER_2312 for 2312
            /// </summary>
            [EnumMember(Value = "2312")]
            NUMBER_2312 = 140,
            /// <summary>
            /// Enum NUMBER_2313 for 2313
            /// </summary>
            [EnumMember(Value = "2313")]
            NUMBER_2313 = 141,
            /// <summary>
            /// Enum NUMBER_2314 for 2314
            /// </summary>
            [EnumMember(Value = "2314")]
            NUMBER_2314 = 142,
            /// <summary>
            /// Enum NUMBER_2315 for 2315
            /// </summary>
            [EnumMember(Value = "2315")]
            NUMBER_2315 = 143,
            /// <summary>
            /// Enum NUMBER_2316 for 2316
            /// </summary>
            [EnumMember(Value = "2316")]
            NUMBER_2316 = 144,
            /// <summary>
            /// Enum NUMBER_2399 for 2399
            /// </summary>
            [EnumMember(Value = "2399")]
            NUMBER_2399 = 145,
            /// <summary>
            /// Enum NUMBER_2401 for 2401
            /// </summary>
            [EnumMember(Value = "2401")]
            NUMBER_2401 = 146,
            /// <summary>
            /// Enum NUMBER_2402 for 2402
            /// </summary>
            [EnumMember(Value = "2402")]
            NUMBER_2402 = 147,
            /// <summary>
            /// Enum NUMBER_2403 for 2403
            /// </summary>
            [EnumMember(Value = "2403")]
            NUMBER_2403 = 148,
            /// <summary>
            /// Enum NUMBER_2404 for 2404
            /// </summary>
            [EnumMember(Value = "2404")]
            NUMBER_2404 = 149,
            /// <summary>
            /// Enum NUMBER_2405 for 2405
            /// </summary>
            [EnumMember(Value = "2405")]
            NUMBER_2405 = 150,
            /// <summary>
            /// Enum NUMBER_2406 for 2406
            /// </summary>
            [EnumMember(Value = "2406")]
            NUMBER_2406 = 151,
            /// <summary>
            /// Enum NUMBER_2407 for 2407
            /// </summary>
            [EnumMember(Value = "2407")]
            NUMBER_2407 = 152,
            /// <summary>
            /// Enum NUMBER_2408 for 2408
            /// </summary>
            [EnumMember(Value = "2408")]
            NUMBER_2408 = 153,
            /// <summary>
            /// Enum NUMBER_2409 for 2409
            /// </summary>
            [EnumMember(Value = "2409")]
            NUMBER_2409 = 154,
            /// <summary>
            /// Enum NUMBER_2410 for 2410
            /// </summary>
            [EnumMember(Value = "2410")]
            NUMBER_2410 = 155,
            /// <summary>
            /// Enum NUMBER_2411 for 2411
            /// </summary>
            [EnumMember(Value = "2411")]
            NUMBER_2411 = 156,
            /// <summary>
            /// Enum NUMBER_2499 for 2499
            /// </summary>
            [EnumMember(Value = "2499")]
            NUMBER_2499 = 157,
            /// <summary>
            /// Enum NUMBER_2501 for 2501
            /// </summary>
            [EnumMember(Value = "2501")]
            NUMBER_2501 = 158,
            /// <summary>
            /// Enum NUMBER_2502 for 2502
            /// </summary>
            [EnumMember(Value = "2502")]
            NUMBER_2502 = 159,
            /// <summary>
            /// Enum NUMBER_2503 for 2503
            /// </summary>
            [EnumMember(Value = "2503")]
            NUMBER_2503 = 160,
            /// <summary>
            /// Enum NUMBER_2504 for 2504
            /// </summary>
            [EnumMember(Value = "2504")]
            NUMBER_2504 = 161,
            /// <summary>
            /// Enum NUMBER_2505 for 2505
            /// </summary>
            [EnumMember(Value = "2505")]
            NUMBER_2505 = 162,
            /// <summary>
            /// Enum NUMBER_2506 for 2506
            /// </summary>
            [EnumMember(Value = "2506")]
            NUMBER_2506 = 163,
            /// <summary>
            /// Enum NUMBER_2507 for 2507
            /// </summary>
            [EnumMember(Value = "2507")]
            NUMBER_2507 = 164,
            /// <summary>
            /// Enum NUMBER_2508 for 2508
            /// </summary>
            [EnumMember(Value = "2508")]
            NUMBER_2508 = 165,
            /// <summary>
            /// Enum NUMBER_2509 for 2509
            /// </summary>
            [EnumMember(Value = "2509")]
            NUMBER_2509 = 166,
            /// <summary>
            /// Enum NUMBER_2510 for 2510
            /// </summary>
            [EnumMember(Value = "2510")]
            NUMBER_2510 = 167,
            /// <summary>
            /// Enum NUMBER_2511 for 2511
            /// </summary>
            [EnumMember(Value = "2511")]
            NUMBER_2511 = 168,
            /// <summary>
            /// Enum NUMBER_2589 for 2589
            /// </summary>
            [EnumMember(Value = "2589")]
            NUMBER_2589 = 169,
            /// <summary>
            /// Enum NUMBER_2599 for 2599
            /// </summary>
            [EnumMember(Value = "2599")]
            NUMBER_2599 = 170,
            /// <summary>
            /// Enum NUMBER_2601 for 2601
            /// </summary>
            [EnumMember(Value = "2601")]
            NUMBER_2601 = 171,
            /// <summary>
            /// Enum NUMBER_2602 for 2602
            /// </summary>
            [EnumMember(Value = "2602")]
            NUMBER_2602 = 172,
            /// <summary>
            /// Enum NUMBER_2603 for 2603
            /// </summary>
            [EnumMember(Value = "2603")]
            NUMBER_2603 = 173,
            /// <summary>
            /// Enum NUMBER_2604 for 2604
            /// </summary>
            [EnumMember(Value = "2604")]
            NUMBER_2604 = 174,
            /// <summary>
            /// Enum NUMBER_2605 for 2605
            /// </summary>
            [EnumMember(Value = "2605")]
            NUMBER_2605 = 175,
            /// <summary>
            /// Enum NUMBER_2606 for 2606
            /// </summary>
            [EnumMember(Value = "2606")]
            NUMBER_2606 = 176,
            /// <summary>
            /// Enum NUMBER_2607 for 2607
            /// </summary>
            [EnumMember(Value = "2607")]
            NUMBER_2607 = 177,
            /// <summary>
            /// Enum NUMBER_2608 for 2608
            /// </summary>
            [EnumMember(Value = "2608")]
            NUMBER_2608 = 178,
            /// <summary>
            /// Enum NUMBER_2609 for 2609
            /// </summary>
            [EnumMember(Value = "2609")]
            NUMBER_2609 = 179,
            /// <summary>
            /// Enum NUMBER_2610 for 2610
            /// </summary>
            [EnumMember(Value = "2610")]
            NUMBER_2610 = 180,
            /// <summary>
            /// Enum NUMBER_2699 for 2699
            /// </summary>
            [EnumMember(Value = "2699")]
            NUMBER_2699 = 181,
            /// <summary>
            /// Enum NUMBER_2701 for 2701
            /// </summary>
            [EnumMember(Value = "2701")]
            NUMBER_2701 = 182,
            /// <summary>
            /// Enum NUMBER_2702 for 2702
            /// </summary>
            [EnumMember(Value = "2702")]
            NUMBER_2702 = 183,
            /// <summary>
            /// Enum NUMBER_2703 for 2703
            /// </summary>
            [EnumMember(Value = "2703")]
            NUMBER_2703 = 184,
            /// <summary>
            /// Enum NUMBER_2704 for 2704
            /// </summary>
            [EnumMember(Value = "2704")]
            NUMBER_2704 = 185,
            /// <summary>
            /// Enum NUMBER_2705 for 2705
            /// </summary>
            [EnumMember(Value = "2705")]
            NUMBER_2705 = 186,
            /// <summary>
            /// Enum NUMBER_2799 for 2799
            /// </summary>
            [EnumMember(Value = "2799")]
            NUMBER_2799 = 187,
            /// <summary>
            /// Enum NUMBER_2801 for 2801
            /// </summary>
            [EnumMember(Value = "2801")]
            NUMBER_2801 = 188,
            /// <summary>
            /// Enum NUMBER_2802 for 2802
            /// </summary>
            [EnumMember(Value = "2802")]
            NUMBER_2802 = 189,
            /// <summary>
            /// Enum NUMBER_2803 for 2803
            /// </summary>
            [EnumMember(Value = "2803")]
            NUMBER_2803 = 190,
            /// <summary>
            /// Enum NUMBER_2804 for 2804
            /// </summary>
            [EnumMember(Value = "2804")]
            NUMBER_2804 = 191,
            /// <summary>
            /// Enum NUMBER_2805 for 2805
            /// </summary>
            [EnumMember(Value = "2805")]
            NUMBER_2805 = 192,
            /// <summary>
            /// Enum NUMBER_2899 for 2899
            /// </summary>
            [EnumMember(Value = "2899")]
            NUMBER_2899 = 193,
            /// <summary>
            /// Enum NUMBER_2901 for 2901
            /// </summary>
            [EnumMember(Value = "2901")]
            NUMBER_2901 = 194,
            /// <summary>
            /// Enum NUMBER_2902 for 2902
            /// </summary>
            [EnumMember(Value = "2902")]
            NUMBER_2902 = 195,
            /// <summary>
            /// Enum NUMBER_2903 for 2903
            /// </summary>
            [EnumMember(Value = "2903")]
            NUMBER_2903 = 196,
            /// <summary>
            /// Enum NUMBER_2904 for 2904
            /// </summary>
            [EnumMember(Value = "2904")]
            NUMBER_2904 = 197,
            /// <summary>
            /// Enum NUMBER_2905 for 2905
            /// </summary>
            [EnumMember(Value = "2905")]
            NUMBER_2905 = 198,
            /// <summary>
            /// Enum NUMBER_2906 for 2906
            /// </summary>
            [EnumMember(Value = "2906")]
            NUMBER_2906 = 199,
            /// <summary>
            /// Enum NUMBER_2999 for 2999
            /// </summary>
            [EnumMember(Value = "2999")]
            NUMBER_2999 = 200,
            /// <summary>
            /// Enum NUMBER_3501 for 3501
            /// </summary>
            [EnumMember(Value = "3501")]
            NUMBER_3501 = 201,
            /// <summary>
            /// Enum NUMBER_3502 for 3502
            /// </summary>
            [EnumMember(Value = "3502")]
            NUMBER_3502 = 202,
            /// <summary>
            /// Enum NUMBER_3503 for 3503
            /// </summary>
            [EnumMember(Value = "3503")]
            NUMBER_3503 = 203,
            /// <summary>
            /// Enum NUMBER_3504 for 3504
            /// </summary>
            [EnumMember(Value = "3504")]
            NUMBER_3504 = 204,
            /// <summary>
            /// Enum NUMBER_3505 for 3505
            /// </summary>
            [EnumMember(Value = "3505")]
            NUMBER_3505 = 205,
            /// <summary>
            /// Enum NUMBER_3510 for 3510
            /// </summary>
            [EnumMember(Value = "3510")]
            NUMBER_3510 = 206,
            /// <summary>
            /// Enum NUMBER_3511 for 3511
            /// </summary>
            [EnumMember(Value = "3511")]
            NUMBER_3511 = 207,
            /// <summary>
            /// Enum NUMBER_3512 for 3512
            /// </summary>
            [EnumMember(Value = "3512")]
            NUMBER_3512 = 208,
            /// <summary>
            /// Enum NUMBER_3513 for 3513
            /// </summary>
            [EnumMember(Value = "3513")]
            NUMBER_3513 = 209,
            /// <summary>
            /// Enum NUMBER_3520 for 3520
            /// </summary>
            [EnumMember(Value = "3520")]
            NUMBER_3520 = 210,
            /// <summary>
            /// Enum NUMBER_3521 for 3521
            /// </summary>
            [EnumMember(Value = "3521")]
            NUMBER_3521 = 211,
            /// <summary>
            /// Enum NUMBER_3522 for 3522
            /// </summary>
            [EnumMember(Value = "3522")]
            NUMBER_3522 = 212,
            /// <summary>
            /// Enum NUMBER_3523 for 3523
            /// </summary>
            [EnumMember(Value = "3523")]
            NUMBER_3523 = 213,
            /// <summary>
            /// Enum NUMBER_3530 for 3530
            /// </summary>
            [EnumMember(Value = "3530")]
            NUMBER_3530 = 214,
            /// <summary>
            /// Enum NUMBER_3531 for 3531
            /// </summary>
            [EnumMember(Value = "3531")]
            NUMBER_3531 = 215,
            /// <summary>
            /// Enum NUMBER_3532 for 3532
            /// </summary>
            [EnumMember(Value = "3532")]
            NUMBER_3532 = 216,
            /// <summary>
            /// Enum NUMBER_3533 for 3533
            /// </summary>
            [EnumMember(Value = "3533")]
            NUMBER_3533 = 217,
            /// <summary>
            /// Enum NUMBER_3540 for 3540
            /// </summary>
            [EnumMember(Value = "3540")]
            NUMBER_3540 = 218,
            /// <summary>
            /// Enum NUMBER_3541 for 3541
            /// </summary>
            [EnumMember(Value = "3541")]
            NUMBER_3541 = 219,
            /// <summary>
            /// Enum NUMBER_3542 for 3542
            /// </summary>
            [EnumMember(Value = "3542")]
            NUMBER_3542 = 220,
            /// <summary>
            /// Enum NUMBER_3543 for 3543
            /// </summary>
            [EnumMember(Value = "3543")]
            NUMBER_3543 = 221,
            /// <summary>
            /// Enum NUMBER_3550 for 3550
            /// </summary>
            [EnumMember(Value = "3550")]
            NUMBER_3550 = 222,
            /// <summary>
            /// Enum NUMBER_3560 for 3560
            /// </summary>
            [EnumMember(Value = "3560")]
            NUMBER_3560 = 223,
            /// <summary>
            /// Enum NUMBER_3561 for 3561
            /// </summary>
            [EnumMember(Value = "3561")]
            NUMBER_3561 = 224,
            /// <summary>
            /// Enum NUMBER_3562 for 3562
            /// </summary>
            [EnumMember(Value = "3562")]
            NUMBER_3562 = 225,
            /// <summary>
            /// Enum NUMBER_3563 for 3563
            /// </summary>
            [EnumMember(Value = "3563")]
            NUMBER_3563 = 226,
            /// <summary>
            /// Enum NUMBER_3564 for 3564
            /// </summary>
            [EnumMember(Value = "3564")]
            NUMBER_3564 = 227,
            /// <summary>
            /// Enum NUMBER_3570 for 3570
            /// </summary>
            [EnumMember(Value = "3570")]
            NUMBER_3570 = 228,
            /// <summary>
            /// Enum NUMBER_3571 for 3571
            /// </summary>
            [EnumMember(Value = "3571")]
            NUMBER_3571 = 229,
            /// <summary>
            /// Enum NUMBER_3572 for 3572
            /// </summary>
            [EnumMember(Value = "3572")]
            NUMBER_3572 = 230,
            /// <summary>
            /// Enum NUMBER_3573 for 3573
            /// </summary>
            [EnumMember(Value = "3573")]
            NUMBER_3573 = 231,
            /// <summary>
            /// Enum NUMBER_3580 for 3580
            /// </summary>
            [EnumMember(Value = "3580")]
            NUMBER_3580 = 232,
            /// <summary>
            /// Enum NUMBER_3581 for 3581
            /// </summary>
            [EnumMember(Value = "3581")]
            NUMBER_3581 = 233,
            /// <summary>
            /// Enum NUMBER_3582 for 3582
            /// </summary>
            [EnumMember(Value = "3582")]
            NUMBER_3582 = 234,
            /// <summary>
            /// Enum NUMBER_3583 for 3583
            /// </summary>
            [EnumMember(Value = "3583")]
            NUMBER_3583 = 235,
            /// <summary>
            /// Enum NUMBER_3599 for 3599
            /// </summary>
            [EnumMember(Value = "3599")]
            NUMBER_3599 = 236,
            /// <summary>
            /// Enum NUMBER_3601 for 3601
            /// </summary>
            [EnumMember(Value = "3601")]
            NUMBER_3601 = 237,
            /// <summary>
            /// Enum NUMBER_3602 for 3602
            /// </summary>
            [EnumMember(Value = "3602")]
            NUMBER_3602 = 238,
            /// <summary>
            /// Enum NUMBER_3603 for 3603
            /// </summary>
            [EnumMember(Value = "3603")]
            NUMBER_3603 = 239,
            /// <summary>
            /// Enum NUMBER_3604 for 3604
            /// </summary>
            [EnumMember(Value = "3604")]
            NUMBER_3604 = 240,
            /// <summary>
            /// Enum NUMBER_3605 for 3605
            /// </summary>
            [EnumMember(Value = "3605")]
            NUMBER_3605 = 241,
            /// <summary>
            /// Enum NUMBER_3606 for 3606
            /// </summary>
            [EnumMember(Value = "3606")]
            NUMBER_3606 = 242,
            /// <summary>
            /// Enum NUMBER_3607 for 3607
            /// </summary>
            [EnumMember(Value = "3607")]
            NUMBER_3607 = 243,
            /// <summary>
            /// Enum NUMBER_3608 for 3608
            /// </summary>
            [EnumMember(Value = "3608")]
            NUMBER_3608 = 244,
            /// <summary>
            /// Enum NUMBER_3609 for 3609
            /// </summary>
            [EnumMember(Value = "3609")]
            NUMBER_3609 = 245,
            /// <summary>
            /// Enum NUMBER_3610 for 3610
            /// </summary>
            [EnumMember(Value = "3610")]
            NUMBER_3610 = 246,
            /// <summary>
            /// Enum NUMBER_3611 for 3611
            /// </summary>
            [EnumMember(Value = "3611")]
            NUMBER_3611 = 247,
            /// <summary>
            /// Enum NUMBER_3612 for 3612
            /// </summary>
            [EnumMember(Value = "3612")]
            NUMBER_3612 = 248,
            /// <summary>
            /// Enum NUMBER_3613 for 3613
            /// </summary>
            [EnumMember(Value = "3613")]
            NUMBER_3613 = 249,
            /// <summary>
            /// Enum NUMBER_3614 for 3614
            /// </summary>
            [EnumMember(Value = "3614")]
            NUMBER_3614 = 250,
            /// <summary>
            /// Enum NUMBER_3615 for 3615
            /// </summary>
            [EnumMember(Value = "3615")]
            NUMBER_3615 = 251,
            /// <summary>
            /// Enum NUMBER_3616 for 3616
            /// </summary>
            [EnumMember(Value = "3616")]
            NUMBER_3616 = 252,
            /// <summary>
            /// Enum NUMBER_3617 for 3617
            /// </summary>
            [EnumMember(Value = "3617")]
            NUMBER_3617 = 253,
            /// <summary>
            /// Enum NUMBER_3618 for 3618
            /// </summary>
            [EnumMember(Value = "3618")]
            NUMBER_3618 = 254,
            /// <summary>
            /// Enum NUMBER_3619 for 3619
            /// </summary>
            [EnumMember(Value = "3619")]
            NUMBER_3619 = 255,
            /// <summary>
            /// Enum NUMBER_3620 for 3620
            /// </summary>
            [EnumMember(Value = "3620")]
            NUMBER_3620 = 256,
            /// <summary>
            /// Enum NUMBER_3621 for 3621
            /// </summary>
            [EnumMember(Value = "3621")]
            NUMBER_3621 = 257,
            /// <summary>
            /// Enum NUMBER_3622 for 3622
            /// </summary>
            [EnumMember(Value = "3622")]
            NUMBER_3622 = 258,
            /// <summary>
            /// Enum NUMBER_3623 for 3623
            /// </summary>
            [EnumMember(Value = "3623")]
            NUMBER_3623 = 259,
            /// <summary>
            /// Enum NUMBER_3699 for 3699
            /// </summary>
            [EnumMember(Value = "3699")]
            NUMBER_3699 = 260,
            /// <summary>
            /// Enum NUMBER_3700 for 3700
            /// </summary>
            [EnumMember(Value = "3700")]
            NUMBER_3700 = 261,
            /// <summary>
            /// Enum NUMBER_3701 for 3701
            /// </summary>
            [EnumMember(Value = "3701")]
            NUMBER_3701 = 262,
            /// <summary>
            /// Enum NUMBER_3702 for 3702
            /// </summary>
            [EnumMember(Value = "3702")]
            NUMBER_3702 = 263,
            /// <summary>
            /// Enum NUMBER_3703 for 3703
            /// </summary>
            [EnumMember(Value = "3703")]
            NUMBER_3703 = 264,
            /// <summary>
            /// Enum NUMBER_3704 for 3704
            /// </summary>
            [EnumMember(Value = "3704")]
            NUMBER_3704 = 265,
            /// <summary>
            /// Enum NUMBER_3705 for 3705
            /// </summary>
            [EnumMember(Value = "3705")]
            NUMBER_3705 = 266,
            /// <summary>
            /// Enum NUMBER_3706 for 3706
            /// </summary>
            [EnumMember(Value = "3706")]
            NUMBER_3706 = 267,
            /// <summary>
            /// Enum NUMBER_3707 for 3707
            /// </summary>
            [EnumMember(Value = "3707")]
            NUMBER_3707 = 268,
            /// <summary>
            /// Enum NUMBER_3799 for 3799
            /// </summary>
            [EnumMember(Value = "3799")]
            NUMBER_3799 = 269,
            /// <summary>
            /// Enum NUMBER_3801 for 3801
            /// </summary>
            [EnumMember(Value = "3801")]
            NUMBER_3801 = 270,
            /// <summary>
            /// Enum NUMBER_3802 for 3802
            /// </summary>
            [EnumMember(Value = "3802")]
            NUMBER_3802 = 271,
            /// <summary>
            /// Enum NUMBER_3803 for 3803
            /// </summary>
            [EnumMember(Value = "3803")]
            NUMBER_3803 = 272,
            /// <summary>
            /// Enum NUMBER_3804 for 3804
            /// </summary>
            [EnumMember(Value = "3804")]
            NUMBER_3804 = 273,
            /// <summary>
            /// Enum NUMBER_3805 for 3805
            /// </summary>
            [EnumMember(Value = "3805")]
            NUMBER_3805 = 274,
            /// <summary>
            /// Enum NUMBER_3806 for 3806
            /// </summary>
            [EnumMember(Value = "3806")]
            NUMBER_3806 = 275,
            /// <summary>
            /// Enum NUMBER_3807 for 3807
            /// </summary>
            [EnumMember(Value = "3807")]
            NUMBER_3807 = 276,
            /// <summary>
            /// Enum NUMBER_3808 for 3808
            /// </summary>
            [EnumMember(Value = "3808")]
            NUMBER_3808 = 277,
            /// <summary>
            /// Enum NUMBER_3809 for 3809
            /// </summary>
            [EnumMember(Value = "3809")]
            NUMBER_3809 = 278,
            /// <summary>
            /// Enum NUMBER_3810 for 3810
            /// </summary>
            [EnumMember(Value = "3810")]
            NUMBER_3810 = 279,
            /// <summary>
            /// Enum NUMBER_3811 for 3811
            /// </summary>
            [EnumMember(Value = "3811")]
            NUMBER_3811 = 280,
            /// <summary>
            /// Enum NUMBER_3812 for 3812
            /// </summary>
            [EnumMember(Value = "3812")]
            NUMBER_3812 = 281,
            /// <summary>
            /// Enum NUMBER_3899 for 3899
            /// </summary>
            [EnumMember(Value = "3899")]
            NUMBER_3899 = 282,
            /// <summary>
            /// Enum NUMBER_3901 for 3901
            /// </summary>
            [EnumMember(Value = "3901")]
            NUMBER_3901 = 283,
            /// <summary>
            /// Enum NUMBER_3902 for 3902
            /// </summary>
            [EnumMember(Value = "3902")]
            NUMBER_3902 = 284,
            /// <summary>
            /// Enum NUMBER_3904 for 3904
            /// </summary>
            [EnumMember(Value = "3904")]
            NUMBER_3904 = 285,
            /// <summary>
            /// Enum NUMBER_3905 for 3905
            /// </summary>
            [EnumMember(Value = "3905")]
            NUMBER_3905 = 286,
            /// <summary>
            /// Enum NUMBER_3907 for 3907
            /// </summary>
            [EnumMember(Value = "3907")]
            NUMBER_3907 = 287,
            /// <summary>
            /// Enum NUMBER_3908 for 3908
            /// </summary>
            [EnumMember(Value = "3908")]
            NUMBER_3908 = 288,
            /// <summary>
            /// Enum NUMBER_3909 for 3909
            /// </summary>
            [EnumMember(Value = "3909")]
            NUMBER_3909 = 289,
            /// <summary>
            /// Enum NUMBER_3910 for 3910
            /// </summary>
            [EnumMember(Value = "3910")]
            NUMBER_3910 = 290,
            /// <summary>
            /// Enum NUMBER_3911 for 3911
            /// </summary>
            [EnumMember(Value = "3911")]
            NUMBER_3911 = 291,
            /// <summary>
            /// Enum NUMBER_3912 for 3912
            /// </summary>
            [EnumMember(Value = "3912")]
            NUMBER_3912 = 292,
            /// <summary>
            /// Enum NUMBER_3913 for 3913
            /// </summary>
            [EnumMember(Value = "3913")]
            NUMBER_3913 = 293,
            /// <summary>
            /// Enum NUMBER_3914 for 3914
            /// </summary>
            [EnumMember(Value = "3914")]
            NUMBER_3914 = 294,
            /// <summary>
            /// Enum NUMBER_3915 for 3915
            /// </summary>
            [EnumMember(Value = "3915")]
            NUMBER_3915 = 295,
            /// <summary>
            /// Enum NUMBER_3916 for 3916
            /// </summary>
            [EnumMember(Value = "3916")]
            NUMBER_3916 = 296,
            /// <summary>
            /// Enum NUMBER_3918 for 3918
            /// </summary>
            [EnumMember(Value = "3918")]
            NUMBER_3918 = 297,
            /// <summary>
            /// Enum NUMBER_3919 for 3919
            /// </summary>
            [EnumMember(Value = "3919")]
            NUMBER_3919 = 298,
            /// <summary>
            /// Enum NUMBER_3920 for 3920
            /// </summary>
            [EnumMember(Value = "3920")]
            NUMBER_3920 = 299,
            /// <summary>
            /// Enum NUMBER_3921 for 3921
            /// </summary>
            [EnumMember(Value = "3921")]
            NUMBER_3921 = 300,
            /// <summary>
            /// Enum NUMBER_3999 for 3999
            /// </summary>
            [EnumMember(Value = "3999")]
            NUMBER_3999 = 301,
            /// <summary>
            /// Enum NUMBER_4001 for 4001
            /// </summary>
            [EnumMember(Value = "4001")]
            NUMBER_4001 = 302,
            /// <summary>
            /// Enum NUMBER_4002 for 4002
            /// </summary>
            [EnumMember(Value = "4002")]
            NUMBER_4002 = 303,
            /// <summary>
            /// Enum NUMBER_4003 for 4003
            /// </summary>
            [EnumMember(Value = "4003")]
            NUMBER_4003 = 304,
            /// <summary>
            /// Enum NUMBER_4004 for 4004
            /// </summary>
            [EnumMember(Value = "4004")]
            NUMBER_4004 = 305,
            /// <summary>
            /// Enum NUMBER_4005 for 4005
            /// </summary>
            [EnumMember(Value = "4005")]
            NUMBER_4005 = 306,
            /// <summary>
            /// Enum NUMBER_4006 for 4006
            /// </summary>
            [EnumMember(Value = "4006")]
            NUMBER_4006 = 307,
            /// <summary>
            /// Enum NUMBER_4007 for 4007
            /// </summary>
            [EnumMember(Value = "4007")]
            NUMBER_4007 = 308,
            /// <summary>
            /// Enum NUMBER_4008 for 4008
            /// </summary>
            [EnumMember(Value = "4008")]
            NUMBER_4008 = 309,
            /// <summary>
            /// Enum NUMBER_4009 for 4009
            /// </summary>
            [EnumMember(Value = "4009")]
            NUMBER_4009 = 310,
            /// <summary>
            /// Enum NUMBER_4099 for 4099
            /// </summary>
            [EnumMember(Value = "4099")]
            NUMBER_4099 = 311,
            /// <summary>
            /// Enum NUMBER_4101 for 4101
            /// </summary>
            [EnumMember(Value = "4101")]
            NUMBER_4101 = 312,
            /// <summary>
            /// Enum NUMBER_4102 for 4102
            /// </summary>
            [EnumMember(Value = "4102")]
            NUMBER_4102 = 313,
            /// <summary>
            /// Enum NUMBER_4103 for 4103
            /// </summary>
            [EnumMember(Value = "4103")]
            NUMBER_4103 = 314,
            /// <summary>
            /// Enum NUMBER_4104 for 4104
            /// </summary>
            [EnumMember(Value = "4104")]
            NUMBER_4104 = 315,
            /// <summary>
            /// Enum NUMBER_4199 for 4199
            /// </summary>
            [EnumMember(Value = "4199")]
            NUMBER_4199 = 316,
            /// <summary>
            /// Enum NUMBER_4801 for 4801
            /// </summary>
            [EnumMember(Value = "4801")]
            NUMBER_4801 = 317,
            /// <summary>
            /// Enum NUMBER_4802 for 4802
            /// </summary>
            [EnumMember(Value = "4802")]
            NUMBER_4802 = 318,
            /// <summary>
            /// Enum NUMBER_4803 for 4803
            /// </summary>
            [EnumMember(Value = "4803")]
            NUMBER_4803 = 319,
            /// <summary>
            /// Enum NUMBER_4804 for 4804
            /// </summary>
            [EnumMember(Value = "4804")]
            NUMBER_4804 = 320,
            /// <summary>
            /// Enum NUMBER_4805 for 4805
            /// </summary>
            [EnumMember(Value = "4805")]
            NUMBER_4805 = 321,
            /// <summary>
            /// Enum NUMBER_4806 for 4806
            /// </summary>
            [EnumMember(Value = "4806")]
            NUMBER_4806 = 322,
            /// <summary>
            /// Enum NUMBER_4807 for 4807
            /// </summary>
            [EnumMember(Value = "4807")]
            NUMBER_4807 = 323,
            /// <summary>
            /// Enum NUMBER_4808 for 4808
            /// </summary>
            [EnumMember(Value = "4808")]
            NUMBER_4808 = 324,
            /// <summary>
            /// Enum NUMBER_4809 for 4809
            /// </summary>
            [EnumMember(Value = "4809")]
            NUMBER_4809 = 325,
            /// <summary>
            /// Enum NUMBER_4810 for 4810
            /// </summary>
            [EnumMember(Value = "4810")]
            NUMBER_4810 = 326,
            /// <summary>
            /// Enum NUMBER_4811 for 4811
            /// </summary>
            [EnumMember(Value = "4811")]
            NUMBER_4811 = 327,
            /// <summary>
            /// Enum NUMBER_4812 for 4812
            /// </summary>
            [EnumMember(Value = "4812")]
            NUMBER_4812 = 328,
            /// <summary>
            /// Enum NUMBER_4813 for 4813
            /// </summary>
            [EnumMember(Value = "4813")]
            NUMBER_4813 = 329,
            /// <summary>
            /// Enum NUMBER_4899 for 4899
            /// </summary>
            [EnumMember(Value = "4899")]
            NUMBER_4899 = 330,
            /// <summary>
            /// Enum NUMBER_4901 for 4901
            /// </summary>
            [EnumMember(Value = "4901")]
            NUMBER_4901 = 331,
            /// <summary>
            /// Enum NUMBER_4902 for 4902
            /// </summary>
            [EnumMember(Value = "4902")]
            NUMBER_4902 = 332,
            /// <summary>
            /// Enum NUMBER_4903 for 4903
            /// </summary>
            [EnumMember(Value = "4903")]
            NUMBER_4903 = 333,
            /// <summary>
            /// Enum NUMBER_4904 for 4904
            /// </summary>
            [EnumMember(Value = "4904")]
            NUMBER_4904 = 334,
            /// <summary>
            /// Enum NUMBER_4999 for 4999
            /// </summary>
            [EnumMember(Value = "4999")]
            NUMBER_4999 = 335,
            /// <summary>
            /// Enum NUMBER_5001 for 5001
            /// </summary>
            [EnumMember(Value = "5001")]
            NUMBER_5001 = 336,
            /// <summary>
            /// Enum NUMBER_5002 for 5002
            /// </summary>
            [EnumMember(Value = "5002")]
            NUMBER_5002 = 337,
            /// <summary>
            /// Enum NUMBER_5003 for 5003
            /// </summary>
            [EnumMember(Value = "5003")]
            NUMBER_5003 = 338,
            /// <summary>
            /// Enum NUMBER_5004 for 5004
            /// </summary>
            [EnumMember(Value = "5004")]
            NUMBER_5004 = 339,
            /// <summary>
            /// Enum NUMBER_5005 for 5005
            /// </summary>
            [EnumMember(Value = "5005")]
            NUMBER_5005 = 340,
            /// <summary>
            /// Enum NUMBER_5006 for 5006
            /// </summary>
            [EnumMember(Value = "5006")]
            NUMBER_5006 = 341,
            /// <summary>
            /// Enum NUMBER_5007 for 5007
            /// </summary>
            [EnumMember(Value = "5007")]
            NUMBER_5007 = 342,
            /// <summary>
            /// Enum NUMBER_5008 for 5008
            /// </summary>
            [EnumMember(Value = "5008")]
            NUMBER_5008 = 343,
            /// <summary>
            /// Enum NUMBER_5009 for 5009
            /// </summary>
            [EnumMember(Value = "5009")]
            NUMBER_5009 = 344,
            /// <summary>
            /// Enum NUMBER_5010 for 5010
            /// </summary>
            [EnumMember(Value = "5010")]
            NUMBER_5010 = 345,
            /// <summary>
            /// Enum NUMBER_5011 for 5011
            /// </summary>
            [EnumMember(Value = "5011")]
            NUMBER_5011 = 346,
            /// <summary>
            /// Enum NUMBER_5012 for 5012
            /// </summary>
            [EnumMember(Value = "5012")]
            NUMBER_5012 = 347,
            /// <summary>
            /// Enum NUMBER_5013 for 5013
            /// </summary>
            [EnumMember(Value = "5013")]
            NUMBER_5013 = 348,
            /// <summary>
            /// Enum NUMBER_5014 for 5014
            /// </summary>
            [EnumMember(Value = "5014")]
            NUMBER_5014 = 349,
            /// <summary>
            /// Enum NUMBER_5015 for 5015
            /// </summary>
            [EnumMember(Value = "5015")]
            NUMBER_5015 = 350,
            /// <summary>
            /// Enum NUMBER_5016 for 5016
            /// </summary>
            [EnumMember(Value = "5016")]
            NUMBER_5016 = 351,
            /// <summary>
            /// Enum NUMBER_5099 for 5099
            /// </summary>
            [EnumMember(Value = "5099")]
            NUMBER_5099 = 352,
            /// <summary>
            /// Enum NUMBER_5101 for 5101
            /// </summary>
            [EnumMember(Value = "5101")]
            NUMBER_5101 = 353,
            /// <summary>
            /// Enum NUMBER_5102 for 5102
            /// </summary>
            [EnumMember(Value = "5102")]
            NUMBER_5102 = 354,
            /// <summary>
            /// Enum NUMBER_5103 for 5103
            /// </summary>
            [EnumMember(Value = "5103")]
            NUMBER_5103 = 355,
            /// <summary>
            /// Enum NUMBER_5104 for 5104
            /// </summary>
            [EnumMember(Value = "5104")]
            NUMBER_5104 = 356,
            /// <summary>
            /// Enum NUMBER_5105 for 5105
            /// </summary>
            [EnumMember(Value = "5105")]
            NUMBER_5105 = 357,
            /// <summary>
            /// Enum NUMBER_5106 for 5106
            /// </summary>
            [EnumMember(Value = "5106")]
            NUMBER_5106 = 358,
            /// <summary>
            /// Enum NUMBER_5107 for 5107
            /// </summary>
            [EnumMember(Value = "5107")]
            NUMBER_5107 = 359,
            /// <summary>
            /// Enum NUMBER_5108 for 5108
            /// </summary>
            [EnumMember(Value = "5108")]
            NUMBER_5108 = 360,
            /// <summary>
            /// Enum NUMBER_5109 for 5109
            /// </summary>
            [EnumMember(Value = "5109")]
            NUMBER_5109 = 361,
            /// <summary>
            /// Enum NUMBER_5110 for 5110
            /// </summary>
            [EnumMember(Value = "5110")]
            NUMBER_5110 = 362,
            /// <summary>
            /// Enum NUMBER_5111 for 5111
            /// </summary>
            [EnumMember(Value = "5111")]
            NUMBER_5111 = 363,
            /// <summary>
            /// Enum NUMBER_5112 for 5112
            /// </summary>
            [EnumMember(Value = "5112")]
            NUMBER_5112 = 364,
            /// <summary>
            /// Enum NUMBER_5113 for 5113
            /// </summary>
            [EnumMember(Value = "5113")]
            NUMBER_5113 = 365,
            /// <summary>
            /// Enum NUMBER_5199 for 5199
            /// </summary>
            [EnumMember(Value = "5199")]
            NUMBER_5199 = 366,
            /// <summary>
            /// Enum NUMBER_5201 for 5201
            /// </summary>
            [EnumMember(Value = "5201")]
            NUMBER_5201 = 367,
            /// <summary>
            /// Enum NUMBER_5202 for 5202
            /// </summary>
            [EnumMember(Value = "5202")]
            NUMBER_5202 = 368,
            /// <summary>
            /// Enum NUMBER_5203 for 5203
            /// </summary>
            [EnumMember(Value = "5203")]
            NUMBER_5203 = 369,
            /// <summary>
            /// Enum NUMBER_5204 for 5204
            /// </summary>
            [EnumMember(Value = "5204")]
            NUMBER_5204 = 370,
            /// <summary>
            /// Enum NUMBER_5205 for 5205
            /// </summary>
            [EnumMember(Value = "5205")]
            NUMBER_5205 = 371,
            /// <summary>
            /// Enum NUMBER_5206 for 5206
            /// </summary>
            [EnumMember(Value = "5206")]
            NUMBER_5206 = 372,
            /// <summary>
            /// Enum NUMBER_5207 for 5207
            /// </summary>
            [EnumMember(Value = "5207")]
            NUMBER_5207 = 373,
            /// <summary>
            /// Enum NUMBER_5208 for 5208
            /// </summary>
            [EnumMember(Value = "5208")]
            NUMBER_5208 = 374,
            /// <summary>
            /// Enum NUMBER_5209 for 5209
            /// </summary>
            [EnumMember(Value = "5209")]
            NUMBER_5209 = 375,
            /// <summary>
            /// Enum NUMBER_5210 for 5210
            /// </summary>
            [EnumMember(Value = "5210")]
            NUMBER_5210 = 376,
            /// <summary>
            /// Enum NUMBER_5211 for 5211
            /// </summary>
            [EnumMember(Value = "5211")]
            NUMBER_5211 = 377,
            /// <summary>
            /// Enum NUMBER_5212 for 5212
            /// </summary>
            [EnumMember(Value = "5212")]
            NUMBER_5212 = 378,
            /// <summary>
            /// Enum NUMBER_5213 for 5213
            /// </summary>
            [EnumMember(Value = "5213")]
            NUMBER_5213 = 379,
            /// <summary>
            /// Enum NUMBER_5214 for 5214
            /// </summary>
            [EnumMember(Value = "5214")]
            NUMBER_5214 = 380,
            /// <summary>
            /// Enum NUMBER_5215 for 5215
            /// </summary>
            [EnumMember(Value = "5215")]
            NUMBER_5215 = 381,
            /// <summary>
            /// Enum NUMBER_5216 for 5216
            /// </summary>
            [EnumMember(Value = "5216")]
            NUMBER_5216 = 382,
            /// <summary>
            /// Enum NUMBER_5217 for 5217
            /// </summary>
            [EnumMember(Value = "5217")]
            NUMBER_5217 = 383,
            /// <summary>
            /// Enum NUMBER_5299 for 5299
            /// </summary>
            [EnumMember(Value = "5299")]
            NUMBER_5299 = 384,
            /// <summary>
            /// Enum NUMBER_5301 for 5301
            /// </summary>
            [EnumMember(Value = "5301")]
            NUMBER_5301 = 385,
            /// <summary>
            /// Enum NUMBER_5302 for 5302
            /// </summary>
            [EnumMember(Value = "5302")]
            NUMBER_5302 = 386,
            /// <summary>
            /// Enum NUMBER_5303 for 5303
            /// </summary>
            [EnumMember(Value = "5303")]
            NUMBER_5303 = 387,
            /// <summary>
            /// Enum NUMBER_5304 for 5304
            /// </summary>
            [EnumMember(Value = "5304")]
            NUMBER_5304 = 388,
            /// <summary>
            /// Enum NUMBER_5305 for 5305
            /// </summary>
            [EnumMember(Value = "5305")]
            NUMBER_5305 = 389,
            /// <summary>
            /// Enum NUMBER_5306 for 5306
            /// </summary>
            [EnumMember(Value = "5306")]
            NUMBER_5306 = 390,
            /// <summary>
            /// Enum NUMBER_5307 for 5307
            /// </summary>
            [EnumMember(Value = "5307")]
            NUMBER_5307 = 391,
            /// <summary>
            /// Enum NUMBER_5309 for 5309
            /// </summary>
            [EnumMember(Value = "5309")]
            NUMBER_5309 = 392,
            /// <summary>
            /// Enum NUMBER_5310 for 5310
            /// </summary>
            [EnumMember(Value = "5310")]
            NUMBER_5310 = 393,
            /// <summary>
            /// Enum NUMBER_5311 for 5311
            /// </summary>
            [EnumMember(Value = "5311")]
            NUMBER_5311 = 394,
            /// <summary>
            /// Enum NUMBER_5399 for 5399
            /// </summary>
            [EnumMember(Value = "5399")]
            NUMBER_5399 = 395,
            /// <summary>
            /// Enum NUMBER_5401 for 5401
            /// </summary>
            [EnumMember(Value = "5401")]
            NUMBER_5401 = 396,
            /// <summary>
            /// Enum NUMBER_5402 for 5402
            /// </summary>
            [EnumMember(Value = "5402")]
            NUMBER_5402 = 397,
            /// <summary>
            /// Enum NUMBER_5403 for 5403
            /// </summary>
            [EnumMember(Value = "5403")]
            NUMBER_5403 = 398,
            /// <summary>
            /// Enum NUMBER_5404 for 5404
            /// </summary>
            [EnumMember(Value = "5404")]
            NUMBER_5404 = 399,
            /// <summary>
            /// Enum NUMBER_5499 for 5499
            /// </summary>
            [EnumMember(Value = "5499")]
            NUMBER_5499 = 400,
            /// <summary>
            /// Enum NUMBER_5501 for 5501
            /// </summary>
            [EnumMember(Value = "5501")]
            NUMBER_5501 = 401,
            /// <summary>
            /// Enum NUMBER_5502 for 5502
            /// </summary>
            [EnumMember(Value = "5502")]
            NUMBER_5502 = 402,
            /// <summary>
            /// Enum NUMBER_5503 for 5503
            /// </summary>
            [EnumMember(Value = "5503")]
            NUMBER_5503 = 403,
            /// <summary>
            /// Enum NUMBER_5510 for 5510
            /// </summary>
            [EnumMember(Value = "5510")]
            NUMBER_5510 = 404,
            /// <summary>
            /// Enum NUMBER_5511 for 5511
            /// </summary>
            [EnumMember(Value = "5511")]
            NUMBER_5511 = 405,
            /// <summary>
            /// Enum NUMBER_5512 for 5512
            /// </summary>
            [EnumMember(Value = "5512")]
            NUMBER_5512 = 406,
            /// <summary>
            /// Enum NUMBER_5520 for 5520
            /// </summary>
            [EnumMember(Value = "5520")]
            NUMBER_5520 = 407,
            /// <summary>
            /// Enum NUMBER_5521 for 5521
            /// </summary>
            [EnumMember(Value = "5521")]
            NUMBER_5521 = 408,
            /// <summary>
            /// Enum NUMBER_5522 for 5522
            /// </summary>
            [EnumMember(Value = "5522")]
            NUMBER_5522 = 409,
            /// <summary>
            /// Enum NUMBER_5599 for 5599
            /// </summary>
            [EnumMember(Value = "5599")]
            NUMBER_5599 = 410,
            /// <summary>
            /// Enum NUMBER_5699 for 5699
            /// </summary>
            [EnumMember(Value = "5699")]
            NUMBER_5699 = 411,
            /// <summary>
            /// Enum NUMBER_5701 for 5701
            /// </summary>
            [EnumMember(Value = "5701")]
            NUMBER_5701 = 412,
            /// <summary>
            /// Enum NUMBER_5702 for 5702
            /// </summary>
            [EnumMember(Value = "5702")]
            NUMBER_5702 = 413,
            /// <summary>
            /// Enum NUMBER_5703 for 5703
            /// </summary>
            [EnumMember(Value = "5703")]
            NUMBER_5703 = 414,
            /// <summary>
            /// Enum NUMBER_5704 for 5704
            /// </summary>
            [EnumMember(Value = "5704")]
            NUMBER_5704 = 415,
            /// <summary>
            /// Enum NUMBER_5705 for 5705
            /// </summary>
            [EnumMember(Value = "5705")]
            NUMBER_5705 = 416,
            /// <summary>
            /// Enum NUMBER_5706 for 5706
            /// </summary>
            [EnumMember(Value = "5706")]
            NUMBER_5706 = 417,
            /// <summary>
            /// Enum NUMBER_5707 for 5707
            /// </summary>
            [EnumMember(Value = "5707")]
            NUMBER_5707 = 418,
            /// <summary>
            /// Enum NUMBER_5708 for 5708
            /// </summary>
            [EnumMember(Value = "5708")]
            NUMBER_5708 = 419,
            /// <summary>
            /// Enum NUMBER_5799 for 5799
            /// </summary>
            [EnumMember(Value = "5799")]
            NUMBER_5799 = 420,
            /// <summary>
            /// Enum NUMBER_5801 for 5801
            /// </summary>
            [EnumMember(Value = "5801")]
            NUMBER_5801 = 421,
            /// <summary>
            /// Enum NUMBER_5802 for 5802
            /// </summary>
            [EnumMember(Value = "5802")]
            NUMBER_5802 = 422,
            /// <summary>
            /// Enum NUMBER_5803 for 5803
            /// </summary>
            [EnumMember(Value = "5803")]
            NUMBER_5803 = 423,
            /// <summary>
            /// Enum NUMBER_5899 for 5899
            /// </summary>
            [EnumMember(Value = "5899")]
            NUMBER_5899 = 424,
            /// <summary>
            /// Enum NUMBER_5999 for 5999
            /// </summary>
            [EnumMember(Value = "5999")]
            NUMBER_5999 = 425,
            /// <summary>
            /// Enum NUMBER_6099 for 6099
            /// </summary>
            [EnumMember(Value = "6099")]
            NUMBER_6099 = 426,
            /// <summary>
            /// Enum NUMBER_6101 for 6101
            /// </summary>
            [EnumMember(Value = "6101")]
            NUMBER_6101 = 427,
            /// <summary>
            /// Enum NUMBER_6102 for 6102
            /// </summary>
            [EnumMember(Value = "6102")]
            NUMBER_6102 = 428,
            /// <summary>
            /// Enum NUMBER_6103 for 6103
            /// </summary>
            [EnumMember(Value = "6103")]
            NUMBER_6103 = 429,
            /// <summary>
            /// Enum NUMBER_6199 for 6199
            /// </summary>
            [EnumMember(Value = "6199")]
            NUMBER_6199 = 430,
            /// <summary>
            /// Enum NUMBER_6201 for 6201
            /// </summary>
            [EnumMember(Value = "6201")]
            NUMBER_6201 = 431,
            /// <summary>
            /// Enum NUMBER_6202 for 6202
            /// </summary>
            [EnumMember(Value = "6202")]
            NUMBER_6202 = 432,
            /// <summary>
            /// Enum NUMBER_6203 for 6203
            /// </summary>
            [EnumMember(Value = "6203")]
            NUMBER_6203 = 433,
            /// <summary>
            /// Enum NUMBER_6204 for 6204
            /// </summary>
            [EnumMember(Value = "6204")]
            NUMBER_6204 = 434,
            /// <summary>
            /// Enum NUMBER_6205 for 6205
            /// </summary>
            [EnumMember(Value = "6205")]
            NUMBER_6205 = 435,
            /// <summary>
            /// Enum NUMBER_6299 for 6299
            /// </summary>
            [EnumMember(Value = "6299")]
            NUMBER_6299 = 436,
            /// <summary>
            /// Enum NUMBER_6300 for 6300
            /// </summary>
            [EnumMember(Value = "6300")]
            NUMBER_6300 = 437,
            /// <summary>
            /// Enum NUMBER_6401 for 6401
            /// </summary>
            [EnumMember(Value = "6401")]
            NUMBER_6401 = 438,
            /// <summary>
            /// Enum NUMBER_6402 for 6402
            /// </summary>
            [EnumMember(Value = "6402")]
            NUMBER_6402 = 439,
            /// <summary>
            /// Enum NUMBER_6403 for 6403
            /// </summary>
            [EnumMember(Value = "6403")]
            NUMBER_6403 = 440,
            /// <summary>
            /// Enum NUMBER_6404 for 6404
            /// </summary>
            [EnumMember(Value = "6404")]
            NUMBER_6404 = 441,
            /// <summary>
            /// Enum NUMBER_6405 for 6405
            /// </summary>
            [EnumMember(Value = "6405")]
            NUMBER_6405 = 442,
            /// <summary>
            /// Enum NUMBER_6406 for 6406
            /// </summary>
            [EnumMember(Value = "6406")]
            NUMBER_6406 = 443,
            /// <summary>
            /// Enum NUMBER_6407 for 6407
            /// </summary>
            [EnumMember(Value = "6407")]
            NUMBER_6407 = 444,
            /// <summary>
            /// Enum NUMBER_6408 for 6408
            /// </summary>
            [EnumMember(Value = "6408")]
            NUMBER_6408 = 445,
            /// <summary>
            /// Enum NUMBER_6409 for 6409
            /// </summary>
            [EnumMember(Value = "6409")]
            NUMBER_6409 = 446,
            /// <summary>
            /// Enum NUMBER_6410 for 6410
            /// </summary>
            [EnumMember(Value = "6410")]
            NUMBER_6410 = 447,
            /// <summary>
            /// Enum NUMBER_6411 for 6411
            /// </summary>
            [EnumMember(Value = "6411")]
            NUMBER_6411 = 448,
            /// <summary>
            /// Enum NUMBER_6499 for 6499
            /// </summary>
            [EnumMember(Value = "6499")]
            NUMBER_6499 = 449,
            /// <summary>
            /// Enum NUMBER_7099 for 7099
            /// </summary>
            [EnumMember(Value = "7099")]
            NUMBER_7099 = 450,
            /// <summary>
            /// Enum NUMBER_7199 for 7199
            /// </summary>
            [EnumMember(Value = "7199")]
            NUMBER_7199 = 451,
            /// <summary>
            /// Enum NUMBER_7201 for 7201
            /// </summary>
            [EnumMember(Value = "7201")]
            NUMBER_7201 = 452,
            /// <summary>
            /// Enum NUMBER_7299 for 7299
            /// </summary>
            [EnumMember(Value = "7299")]
            NUMBER_7299 = 453,
            /// <summary>
            /// Enum NUMBER_7399 for 7399
            /// </summary>
            [EnumMember(Value = "7399")]
            NUMBER_7399 = 454,
            /// <summary>
            /// Enum NUMBER_8001 for 8001
            /// </summary>
            [EnumMember(Value = "8001")]
            NUMBER_8001 = 455,
            /// <summary>
            /// Enum NUMBER_8003 for 8003
            /// </summary>
            [EnumMember(Value = "8003")]
            NUMBER_8003 = 456,
            /// <summary>
            /// Enum NUMBER_8004 for 8004
            /// </summary>
            [EnumMember(Value = "8004")]
            NUMBER_8004 = 457,
            /// <summary>
            /// Enum NUMBER_8005 for 8005
            /// </summary>
            [EnumMember(Value = "8005")]
            NUMBER_8005 = 458,
            /// <summary>
            /// Enum NUMBER_8100 for 8100
            /// </summary>
            [EnumMember(Value = "8100")]
            NUMBER_8100 = 459,
            /// <summary>
            /// Enum NUMBER_8101 for 8101
            /// </summary>
            [EnumMember(Value = "8101")]
            NUMBER_8101 = 460,
            /// <summary>
            /// Enum NUMBER_8102 for 8102
            /// </summary>
            [EnumMember(Value = "8102")]
            NUMBER_8102 = 461        }
}
