/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for a code that identifies the type of bias that motivated the offense, if any. Includes all NIBRS codes, plus additional codes.
        /// </summary>
        /// <value>A data type for a code that identifies the type of bias that motivated the offense, if any. Includes all NIBRS codes, plus additional codes.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NdexBiasMotivationCodeSimpleType
        {
            /// <summary>
            /// Enum ANTIAMERICANINDIANALASKANNATIVEEnum for ANTIAMERICAN INDIAN_ ALASKAN NATIVE
            /// </summary>
            [EnumMember(Value = "ANTIAMERICAN INDIAN_ ALASKAN NATIVE")]
            ANTIAMERICANINDIANALASKANNATIVEEnum = 0,
            /// <summary>
            /// Enum ANTIARABEnum for ANTIARAB
            /// </summary>
            [EnumMember(Value = "ANTIARAB")]
            ANTIARABEnum = 1,
            /// <summary>
            /// Enum ANTIASIANEnum for ANTIASIAN
            /// </summary>
            [EnumMember(Value = "ANTIASIAN")]
            ANTIASIANEnum = 2,
            /// <summary>
            /// Enum ANTIATHEISTAGNOSTICEnum for ANTIATHEIST_AGNOSTIC
            /// </summary>
            [EnumMember(Value = "ANTIATHEIST_AGNOSTIC")]
            ANTIATHEISTAGNOSTICEnum = 3,
            /// <summary>
            /// Enum ANTIBISEXUALEnum for ANTIBISEXUAL
            /// </summary>
            [EnumMember(Value = "ANTIBISEXUAL")]
            ANTIBISEXUALEnum = 4,
            /// <summary>
            /// Enum ANTIBLACKAFRICANAMERICANEnum for ANTIBLACK_AFRICAN AMERICAN
            /// </summary>
            [EnumMember(Value = "ANTIBLACK_AFRICAN AMERICAN")]
            ANTIBLACKAFRICANAMERICANEnum = 5,
            /// <summary>
            /// Enum ANTIBUDDHISTEnum for ANTIBUDDHIST
            /// </summary>
            [EnumMember(Value = "ANTIBUDDHIST")]
            ANTIBUDDHISTEnum = 6,
            /// <summary>
            /// Enum ANTICATHOLICEnum for ANTICATHOLIC
            /// </summary>
            [EnumMember(Value = "ANTICATHOLIC")]
            ANTICATHOLICEnum = 7,
            /// <summary>
            /// Enum ANTIDISABLEDEnum for ANTIDISABLED
            /// </summary>
            [EnumMember(Value = "ANTIDISABLED")]
            ANTIDISABLEDEnum = 8,
            /// <summary>
            /// Enum ANTIEASTERNORTHODOXEnum for ANTIEASTERNORTHODOX
            /// </summary>
            [EnumMember(Value = "ANTIEASTERNORTHODOX")]
            ANTIEASTERNORTHODOXEnum = 9,
            /// <summary>
            /// Enum ANTIFEMALEEnum for ANTIFEMALE
            /// </summary>
            [EnumMember(Value = "ANTIFEMALE")]
            ANTIFEMALEEnum = 10,
            /// <summary>
            /// Enum ANTIFEMALEHOMOSEXUALEnum for ANTIFEMALE HOMOSEXUAL
            /// </summary>
            [EnumMember(Value = "ANTIFEMALE HOMOSEXUAL")]
            ANTIFEMALEHOMOSEXUALEnum = 11,
            /// <summary>
            /// Enum ANTIGENDERNONCONFORMINGEnum for ANTIGENDER_NONCONFORMING
            /// </summary>
            [EnumMember(Value = "ANTIGENDER_NONCONFORMING")]
            ANTIGENDERNONCONFORMINGEnum = 12,
            /// <summary>
            /// Enum ANTIHETEROSEXUALEnum for ANTIHETEROSEXUAL
            /// </summary>
            [EnumMember(Value = "ANTIHETEROSEXUAL")]
            ANTIHETEROSEXUALEnum = 13,
            /// <summary>
            /// Enum ANTIHINDUEnum for ANTIHINDU
            /// </summary>
            [EnumMember(Value = "ANTIHINDU")]
            ANTIHINDUEnum = 14,
            /// <summary>
            /// Enum ANTIHISPANICLATINOEnum for ANTIHISPANIC_LATINO
            /// </summary>
            [EnumMember(Value = "ANTIHISPANIC_LATINO")]
            ANTIHISPANICLATINOEnum = 15,
            /// <summary>
            /// Enum ANTIHOMOSEXUALEnum for ANTIHOMOSEXUAL
            /// </summary>
            [EnumMember(Value = "ANTIHOMOSEXUAL")]
            ANTIHOMOSEXUALEnum = 16,
            /// <summary>
            /// Enum ANTIISLAMICEnum for ANTIISLAMIC
            /// </summary>
            [EnumMember(Value = "ANTIISLAMIC")]
            ANTIISLAMICEnum = 17,
            /// <summary>
            /// Enum ANTIJEHOVAHWITNESSEnum for ANTIJEHOVAHWITNESS
            /// </summary>
            [EnumMember(Value = "ANTIJEHOVAHWITNESS")]
            ANTIJEHOVAHWITNESSEnum = 18,
            /// <summary>
            /// Enum ANTIJEWISHEnum for ANTIJEWISH
            /// </summary>
            [EnumMember(Value = "ANTIJEWISH")]
            ANTIJEWISHEnum = 19,
            /// <summary>
            /// Enum ANTIMALEEnum for ANTIMALE
            /// </summary>
            [EnumMember(Value = "ANTIMALE")]
            ANTIMALEEnum = 20,
            /// <summary>
            /// Enum ANTIMALEHOMOSEXUALEnum for ANTIMALE HOMOSEXUAL
            /// </summary>
            [EnumMember(Value = "ANTIMALE HOMOSEXUAL")]
            ANTIMALEHOMOSEXUALEnum = 21,
            /// <summary>
            /// Enum ANTIMENTALDISABILITYEnum for ANTIMENTAL DISABILITY
            /// </summary>
            [EnumMember(Value = "ANTIMENTAL DISABILITY")]
            ANTIMENTALDISABILITYEnum = 22,
            /// <summary>
            /// Enum ANTIMORMONEnum for ANTIMORMON
            /// </summary>
            [EnumMember(Value = "ANTIMORMON")]
            ANTIMORMONEnum = 23,
            /// <summary>
            /// Enum ANTIMULTIRACIALGROUPEnum for ANTIMULTIRACIAL GROUP
            /// </summary>
            [EnumMember(Value = "ANTIMULTIRACIAL GROUP")]
            ANTIMULTIRACIALGROUPEnum = 24,
            /// <summary>
            /// Enum ANTIMULTIRELIGIOUSGROUPEnum for ANTIMULTIRELIGIOUS GROUP
            /// </summary>
            [EnumMember(Value = "ANTIMULTIRELIGIOUS GROUP")]
            ANTIMULTIRELIGIOUSGROUPEnum = 25,
            /// <summary>
            /// Enum ANTINATIVEHAWAIIANOTHERPACIFICISLANDEREnum for ANTINATIVEHAWAIIAN_OTHERPACIFICISLANDER
            /// </summary>
            [EnumMember(Value = "ANTINATIVEHAWAIIAN_OTHERPACIFICISLANDER")]
            ANTINATIVEHAWAIIANOTHERPACIFICISLANDEREnum = 26,
            /// <summary>
            /// Enum ANTIOTHERCHRISTIANEnum for ANTIOTHER CHRISTIAN
            /// </summary>
            [EnumMember(Value = "ANTIOTHER CHRISTIAN")]
            ANTIOTHERCHRISTIANEnum = 27,
            /// <summary>
            /// Enum ANTIOTHERETHNICITYNATIONALORIGINEnum for ANTIOTHER ETHNICITY_NATIONAL ORIGIN
            /// </summary>
            [EnumMember(Value = "ANTIOTHER ETHNICITY_NATIONAL ORIGIN")]
            ANTIOTHERETHNICITYNATIONALORIGINEnum = 28,
            /// <summary>
            /// Enum ANTIOTHERRELIGIONEnum for ANTIOTHER RELIGION
            /// </summary>
            [EnumMember(Value = "ANTIOTHER RELIGION")]
            ANTIOTHERRELIGIONEnum = 29,
            /// <summary>
            /// Enum ANTIPHYSICALDISABILITYEnum for ANTIPHYSICAL DISABILITY
            /// </summary>
            [EnumMember(Value = "ANTIPHYSICAL DISABILITY")]
            ANTIPHYSICALDISABILITYEnum = 30,
            /// <summary>
            /// Enum ANTIPROTESTANTEnum for ANTIPROTESTANT
            /// </summary>
            [EnumMember(Value = "ANTIPROTESTANT")]
            ANTIPROTESTANTEnum = 31,
            /// <summary>
            /// Enum ANTISIKHEnum for ANTISIKH
            /// </summary>
            [EnumMember(Value = "ANTISIKH")]
            ANTISIKHEnum = 32,
            /// <summary>
            /// Enum ANTITRANSGENDEREnum for ANTITRANSGENDER
            /// </summary>
            [EnumMember(Value = "ANTITRANSGENDER")]
            ANTITRANSGENDEREnum = 33,
            /// <summary>
            /// Enum ANTIWHITEEnum for ANTIWHITE
            /// </summary>
            [EnumMember(Value = "ANTIWHITE")]
            ANTIWHITEEnum = 34,
            /// <summary>
            /// Enum GENDERBIASEnum for GENDER BIAS
            /// </summary>
            [EnumMember(Value = "GENDER BIAS")]
            GENDERBIASEnum = 35,
            /// <summary>
            /// Enum NONEEnum for NONE
            /// </summary>
            [EnumMember(Value = "NONE")]
            NONEEnum = 36,
            /// <summary>
            /// Enum POLITICALAFFILIATIONBIASEnum for POLITICAL AFFILIATION BIAS
            /// </summary>
            [EnumMember(Value = "POLITICAL AFFILIATION BIAS")]
            POLITICALAFFILIATIONBIASEnum = 37,
            /// <summary>
            /// Enum UNKNOWNEnum for UNKNOWN
            /// </summary>
            [EnumMember(Value = "UNKNOWN")]
            UNKNOWNEnum = 38        }
}
