/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for a code that identifies a type of musical instrument.
        /// </summary>
        /// <value>A data type for a code that identifies a type of musical instrument.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NdexMusicalInstrumentCategoryCodeSimpleType
        {
            /// <summary>
            /// Enum ACCORDIONEnum for ACCORDION
            /// </summary>
            [EnumMember(Value = "ACCORDION")]
            ACCORDIONEnum = 0,
            /// <summary>
            /// Enum AUTOHARPEnum for AUTOHARP
            /// </summary>
            [EnumMember(Value = "AUTOHARP")]
            AUTOHARPEnum = 1,
            /// <summary>
            /// Enum BAGPIPESEnum for BAGPIPES
            /// </summary>
            [EnumMember(Value = "BAGPIPES")]
            BAGPIPESEnum = 2,
            /// <summary>
            /// Enum BANJOEnum for BANJO
            /// </summary>
            [EnumMember(Value = "BANJO")]
            BANJOEnum = 3,
            /// <summary>
            /// Enum BARITONEEnum for BARITONE
            /// </summary>
            [EnumMember(Value = "BARITONE")]
            BARITONEEnum = 4,
            /// <summary>
            /// Enum BASSEnum for BASS
            /// </summary>
            [EnumMember(Value = "BASS")]
            BASSEnum = 5,
            /// <summary>
            /// Enum BASSOONEnum for BASSOON
            /// </summary>
            [EnumMember(Value = "BASSOON")]
            BASSOONEnum = 6,
            /// <summary>
            /// Enum BELLSEnum for BELLS
            /// </summary>
            [EnumMember(Value = "BELLS")]
            BELLSEnum = 7,
            /// <summary>
            /// Enum BELLSMARCHINGBANDEnum for BELLS_ MARCHING BAND
            /// </summary>
            [EnumMember(Value = "BELLS_ MARCHING BAND")]
            BELLSMARCHINGBANDEnum = 8,
            /// <summary>
            /// Enum BELLSORCHESTRAEnum for BELLS_ORCHESTRA
            /// </summary>
            [EnumMember(Value = "BELLS_ORCHESTRA")]
            BELLSORCHESTRAEnum = 9,
            /// <summary>
            /// Enum BUGLEEnum for BUGLE
            /// </summary>
            [EnumMember(Value = "BUGLE")]
            BUGLEEnum = 10,
            /// <summary>
            /// Enum CELLOEnum for CELLO
            /// </summary>
            [EnumMember(Value = "CELLO")]
            CELLOEnum = 11,
            /// <summary>
            /// Enum CLARINETEnum for CLARINET
            /// </summary>
            [EnumMember(Value = "CLARINET")]
            CLARINETEnum = 12,
            /// <summary>
            /// Enum CORNETEnum for CORNET
            /// </summary>
            [EnumMember(Value = "CORNET")]
            CORNETEnum = 13,
            /// <summary>
            /// Enum CYMBALEnum for CYMBAL
            /// </summary>
            [EnumMember(Value = "CYMBAL")]
            CYMBALEnum = 14,
            /// <summary>
            /// Enum DRUMEnum for DRUM
            /// </summary>
            [EnumMember(Value = "DRUM")]
            DRUMEnum = 15,
            /// <summary>
            /// Enum FIDDLEEnum for FIDDLE
            /// </summary>
            [EnumMember(Value = "FIDDLE")]
            FIDDLEEnum = 16,
            /// <summary>
            /// Enum FLUTEEnum for FLUTE
            /// </summary>
            [EnumMember(Value = "FLUTE")]
            FLUTEEnum = 17,
            /// <summary>
            /// Enum GUITAREnum for GUITAR
            /// </summary>
            [EnumMember(Value = "GUITAR")]
            GUITAREnum = 18,
            /// <summary>
            /// Enum HARMONICAEnum for HARMONICA
            /// </summary>
            [EnumMember(Value = "HARMONICA")]
            HARMONICAEnum = 19,
            /// <summary>
            /// Enum HARPEnum for HARP
            /// </summary>
            [EnumMember(Value = "HARP")]
            HARPEnum = 20,
            /// <summary>
            /// Enum HORNEnum for HORN
            /// </summary>
            [EnumMember(Value = "HORN")]
            HORNEnum = 21,
            /// <summary>
            /// Enum INSTRUMENTSTANDEnum for INSTRUMENT_STAND
            /// </summary>
            [EnumMember(Value = "INSTRUMENT_STAND")]
            INSTRUMENTSTANDEnum = 22,
            /// <summary>
            /// Enum KEYBOARDMUSICALEnum for KEYBOARD_MUSICAL
            /// </summary>
            [EnumMember(Value = "KEYBOARD_MUSICAL")]
            KEYBOARDMUSICALEnum = 23,
            /// <summary>
            /// Enum MANDOLINEnum for MANDOLIN
            /// </summary>
            [EnumMember(Value = "MANDOLIN")]
            MANDOLINEnum = 24,
            /// <summary>
            /// Enum MELLOPHONEEnum for MELLOPHONE
            /// </summary>
            [EnumMember(Value = "MELLOPHONE")]
            MELLOPHONEEnum = 25,
            /// <summary>
            /// Enum MUSICSTANDEnum for MUSIC_STAND
            /// </summary>
            [EnumMember(Value = "MUSIC_STAND")]
            MUSICSTANDEnum = 26,
            /// <summary>
            /// Enum MUSICALINSTRUMENTCASEEnum for MUSICAL INSTRUMENT CASE
            /// </summary>
            [EnumMember(Value = "MUSICAL INSTRUMENT CASE")]
            MUSICALINSTRUMENTCASEEnum = 27,
            /// <summary>
            /// Enum OBOEEnum for OBOE
            /// </summary>
            [EnumMember(Value = "OBOE")]
            OBOEEnum = 28,
            /// <summary>
            /// Enum ORGANEnum for ORGAN
            /// </summary>
            [EnumMember(Value = "ORGAN")]
            ORGANEnum = 29,
            /// <summary>
            /// Enum PIANOEnum for PIANO
            /// </summary>
            [EnumMember(Value = "PIANO")]
            PIANOEnum = 30,
            /// <summary>
            /// Enum PICCOLOEnum for PICCOLO
            /// </summary>
            [EnumMember(Value = "PICCOLO")]
            PICCOLOEnum = 31,
            /// <summary>
            /// Enum RECORDEREnum for RECORDER
            /// </summary>
            [EnumMember(Value = "RECORDER")]
            RECORDEREnum = 32,
            /// <summary>
            /// Enum SAXOPHONEEnum for SAXOPHONE
            /// </summary>
            [EnumMember(Value = "SAXOPHONE")]
            SAXOPHONEEnum = 33,
            /// <summary>
            /// Enum SOUSAPHONEEnum for SOUSAPHONE
            /// </summary>
            [EnumMember(Value = "SOUSAPHONE")]
            SOUSAPHONEEnum = 34,
            /// <summary>
            /// Enum SYNTHESIZEREnum for SYNTHESIZER
            /// </summary>
            [EnumMember(Value = "SYNTHESIZER")]
            SYNTHESIZEREnum = 35,
            /// <summary>
            /// Enum TROMBONEEnum for TROMBONE
            /// </summary>
            [EnumMember(Value = "TROMBONE")]
            TROMBONEEnum = 36,
            /// <summary>
            /// Enum TRUMPETEnum for TRUMPET
            /// </summary>
            [EnumMember(Value = "TRUMPET")]
            TRUMPETEnum = 37,
            /// <summary>
            /// Enum TUBAEnum for TUBA
            /// </summary>
            [EnumMember(Value = "TUBA")]
            TUBAEnum = 38,
            /// <summary>
            /// Enum UKULELEEnum for UKULELE
            /// </summary>
            [EnumMember(Value = "UKULELE")]
            UKULELEEnum = 39,
            /// <summary>
            /// Enum VIOLAEnum for VIOLA
            /// </summary>
            [EnumMember(Value = "VIOLA")]
            VIOLAEnum = 40,
            /// <summary>
            /// Enum VIOLINEnum for VIOLIN
            /// </summary>
            [EnumMember(Value = "VIOLIN")]
            VIOLINEnum = 41,
            /// <summary>
            /// Enum XYLOPHONEEnum for XYLOPHONE
            /// </summary>
            [EnumMember(Value = "XYLOPHONE")]
            XYLOPHONEEnum = 42        }
}
