/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for weapons with which a subject may be armed with upon apprehension.
        /// </summary>
        /// <value>A data type for weapons with which a subject may be armed with upon apprehension.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum UcrArresteeWeaponCodeSimpleType
        {
            /// <summary>
            /// Enum NUMBER_01 for 01
            /// </summary>
            [EnumMember(Value = "01")]
            NUMBER_01 = 0,
            /// <summary>
            /// Enum NUMBER_11 for 11
            /// </summary>
            [EnumMember(Value = "11")]
            NUMBER_11 = 1,
            /// <summary>
            /// Enum _11AEnum for 11A
            /// </summary>
            [EnumMember(Value = "11A")]
            _11AEnum = 2,
            /// <summary>
            /// Enum NUMBER_12 for 12
            /// </summary>
            [EnumMember(Value = "12")]
            NUMBER_12 = 3,
            /// <summary>
            /// Enum _12AEnum for 12A
            /// </summary>
            [EnumMember(Value = "12A")]
            _12AEnum = 4,
            /// <summary>
            /// Enum NUMBER_13 for 13
            /// </summary>
            [EnumMember(Value = "13")]
            NUMBER_13 = 5,
            /// <summary>
            /// Enum _13AEnum for 13A
            /// </summary>
            [EnumMember(Value = "13A")]
            _13AEnum = 6,
            /// <summary>
            /// Enum NUMBER_14 for 14
            /// </summary>
            [EnumMember(Value = "14")]
            NUMBER_14 = 7,
            /// <summary>
            /// Enum _14AEnum for 14A
            /// </summary>
            [EnumMember(Value = "14A")]
            _14AEnum = 8,
            /// <summary>
            /// Enum NUMBER_15 for 15
            /// </summary>
            [EnumMember(Value = "15")]
            NUMBER_15 = 9,
            /// <summary>
            /// Enum _15AEnum for 15A
            /// </summary>
            [EnumMember(Value = "15A")]
            _15AEnum = 10,
            /// <summary>
            /// Enum NUMBER_16 for 16
            /// </summary>
            [EnumMember(Value = "16")]
            NUMBER_16 = 11,
            /// <summary>
            /// Enum NUMBER_17 for 17
            /// </summary>
            [EnumMember(Value = "17")]
            NUMBER_17 = 12        }
}
