/*
 * NiemTypes
 *
 * NIEM Types for the EIDO
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace NiemTypes
{ 
        /// <summary>
        /// A data type for kinds of weapons or forces used by a subject in committing an offense.
        /// </summary>
        /// <value>A data type for kinds of weapons or forces used by a subject in committing an offense.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum UcrForceCategoryCodeSimpleType
        {
            /// <summary>
            /// Enum NUMBER_11 for 11
            /// </summary>
            [EnumMember(Value = "11")]
            NUMBER_11 = 0,
            /// <summary>
            /// Enum _11AEnum for 11A
            /// </summary>
            [EnumMember(Value = "11A")]
            _11AEnum = 1,
            /// <summary>
            /// Enum NUMBER_12 for 12
            /// </summary>
            [EnumMember(Value = "12")]
            NUMBER_12 = 2,
            /// <summary>
            /// Enum _12AEnum for 12A
            /// </summary>
            [EnumMember(Value = "12A")]
            _12AEnum = 3,
            /// <summary>
            /// Enum NUMBER_13 for 13
            /// </summary>
            [EnumMember(Value = "13")]
            NUMBER_13 = 4,
            /// <summary>
            /// Enum _13AEnum for 13A
            /// </summary>
            [EnumMember(Value = "13A")]
            _13AEnum = 5,
            /// <summary>
            /// Enum NUMBER_14 for 14
            /// </summary>
            [EnumMember(Value = "14")]
            NUMBER_14 = 6,
            /// <summary>
            /// Enum _14AEnum for 14A
            /// </summary>
            [EnumMember(Value = "14A")]
            _14AEnum = 7,
            /// <summary>
            /// Enum NUMBER_15 for 15
            /// </summary>
            [EnumMember(Value = "15")]
            NUMBER_15 = 8,
            /// <summary>
            /// Enum _15AEnum for 15A
            /// </summary>
            [EnumMember(Value = "15A")]
            _15AEnum = 9,
            /// <summary>
            /// Enum NUMBER_20 for 20
            /// </summary>
            [EnumMember(Value = "20")]
            NUMBER_20 = 10,
            /// <summary>
            /// Enum NUMBER_30 for 30
            /// </summary>
            [EnumMember(Value = "30")]
            NUMBER_30 = 11,
            /// <summary>
            /// Enum NUMBER_35 for 35
            /// </summary>
            [EnumMember(Value = "35")]
            NUMBER_35 = 12,
            /// <summary>
            /// Enum NUMBER_40 for 40
            /// </summary>
            [EnumMember(Value = "40")]
            NUMBER_40 = 13,
            /// <summary>
            /// Enum NUMBER_50 for 50
            /// </summary>
            [EnumMember(Value = "50")]
            NUMBER_50 = 14,
            /// <summary>
            /// Enum NUMBER_60 for 60
            /// </summary>
            [EnumMember(Value = "60")]
            NUMBER_60 = 15,
            /// <summary>
            /// Enum NUMBER_65 for 65
            /// </summary>
            [EnumMember(Value = "65")]
            NUMBER_65 = 16,
            /// <summary>
            /// Enum NUMBER_70 for 70
            /// </summary>
            [EnumMember(Value = "70")]
            NUMBER_70 = 17,
            /// <summary>
            /// Enum NUMBER_85 for 85
            /// </summary>
            [EnumMember(Value = "85")]
            NUMBER_85 = 18,
            /// <summary>
            /// Enum NUMBER_90 for 90
            /// </summary>
            [EnumMember(Value = "90")]
            NUMBER_90 = 19,
            /// <summary>
            /// Enum NUMBER_95 for 95
            /// </summary>
            [EnumMember(Value = "95")]
            NUMBER_95 = 20,
            /// <summary>
            /// Enum NUMBER_99 for 99
            /// </summary>
            [EnumMember(Value = "99")]
            NUMBER_99 = 21        }
}
